### ISSUE TITLE
[MariaDB] Keyvault secrets

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1015]
After creation of a new MariaDB database server I would expect that secrets created in Keyvault are directly useable to connect. Unfortunately it turns out that username secret only contains the username and not the required format <username>@<hostname>. Beside of this it would also make sense to have a third secret which describes MariaDB server fqdn similar than PostgreSQL Flexible server.

For backward compatibillity I suggest we create a new secret with name login-name, so it won't break existing deployments.

existing secrets:
- username
- password

secrets to be added:
- login name (contains login name in format <username>@<hostname>)
- fqdn (contains hostname for MariaDB server e.g. example.mariadb.database.azure.com)

**Comment by arnaudlh** [comment]
Thanks for the suggestion @wasfree, is that something you want to contribute on, should I assign to you?

**Comment by wasfree** [comment]
@arnaudlh yes, will raise an PR soon.
