### ISSUE TITLE
[AppService] support storage account reference in storage_account block

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1029]
Right now its not possible to reference storage accounts in AppService [storage_account](https://github.com/aztfmod/terraform-azurerm-caf/blob/c9a9eed6f3c908bd97ad706f23b42f5953a6859d/modules/webapps/appservice/module.tf#L159) block. This means we have to provide the final storage account name and access_key in our configuration. It would be better if we could reference a storage account by key and use name and access_key from there.

Potentioal configuration could look like this: 
```
app_services = {
    corporate = {
        ...
        settings = {
            storage_account = {
                name                 = "example"
                type                 = "AzureFiles"
                storage_account_key  = "sa1"
                share_name           = "example-share"
            }
        }
        ...
    }
}

**Comment by LaurentLesle** [comment]
Added to 5.5.5
