### ISSUE TITLE
Add support for VM extension KeyVaultForWindows

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/terraform-azurerm-caf#1035]
The [KeyVaultForWindows](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/key-vault-windows) extension is helpful for getting certificates onto machines in a Windows IaaS environment.  

This is an enhancement request to integrate support for this extension in the CAF module.

Please assign to me and I will submit PR with the update.

**Comment by arnaudlh** [comment]
hi @jleonelion, Id recommend you have a look at the branch AL-azurerm2931 as we introduce a new way to call for VM extension which improves significantly plan times!

**Comment by jleonelion** [comment]
Closing issue.  Changes have been merged.
