### ISSUE TITLE
Allow UserAssigned identity for automation account

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/terraform-azurerm-caf#1037]
CAF module does not support associating a managed identity with an automation account resource.  This is an enhancement request to add a dynamic [identity block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account#identity) to the [automation module](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/automation/module.tf#L12-L19)

You can assign to me and I will include the update in PR.

**Comment by arnaudlh** [comment]
Thanks for volunteering @jleonelion, assigned to you!

**Comment by LaurentLesle** [comment]
closing as duplicates of #474
