### ISSUE TITLE
Add support for Azure Batch

### ISSUE THREAD

**Issue by bobalong79** [aztfmod/terraform-azurerm-caf#1038]
Hi @arnaudlh and @LaurentLesle 

I'm opening this issue to track adding support for Azure Batch Account/Application/Certificate/Job/Pool

I'm happy to have a go at adding this myself... should it go into the "compute" directory? Say`compute/batch`?

**Comment by arnaudlh** [comment]
Makes sense to me @bobalong79. I will assign to you for tracking :)
