### ISSUE TITLE
Errors creating Azure firewall with management IP for forced tunneling

### ISSUE THREAD

**Issue by dimitrifc** [aztfmod/terraform-azurerm-caf#1069]
When trying to create an Azure Firewall with a management IP for a forced tunneling I receive the following error:
╷
│ Error: Invalid index
│ 
│   on /home/vscode/.terraform.cache/non-prd/modules/solution/modules/networking/firewall/module.tf line 73, in resource "azurerm_firewall" "fw":
│   73:       public_ip_address_id = try(management_ip_configuration.value.public_ip_address_id, null) != null ? management_ip_configuration.value.public_ip_address_id : var.public_ip_addresses[management_ip_configuration.value.public_ip_key].id
│     ├────────────────
│     │ management_ip_configuration.value.public_ip_key is "pip2"
│     │ var.public_ip_addresses is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.
╵

It's also not possible to create a subnet named exactly AzureFirewallManagementSubnet as necessary according to the [documentation](https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling) because the naming module does not have an exemption.

I submitted a PR to solve both issues.

**Comment by arnaudlh** [comment]
Closing as fixed!
