### ISSUE TITLE
azurerm_virtual_network_gateway - Enhance P2S / Point-2Site configuration

### ISSUE THREAD

**Issue by schoenr79** [aztfmod/terraform-azurerm-caf#1098]
During integration of a virtual network gateway with a point to site client configuration i discovered that only azure certificate is supported.

A look into the provider resource [azurerm_virtual_network_gateway](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway#vpn_client_configuration) shows, that there are more attributes supported now:

- vpn_auth_types
- vpn_client_protocols
- aad_audience
- aad_issuer
- aad_tenant
- radius_server_address
- radius_server_secret

The fields mentioned above are required to support a more common point 2 site configuration and makes the module more aligned to the base resource

**Comment by arnaudlh** [comment]
Thanks for the issue and thanks for the fix :)

**Comment by arnaudlh** [comment]
Closing as merged!
