### ISSUE TITLE
Azure Firewall: NAT Collection rules not working - Cannot specify destination address public IP key

### ISSUE THREAD

**Issue by sponte** [aztfmod/terraform-azurerm-caf#1150]
We're trying to deploy Azure Firewall Policy NAT Rule Collection Group and we want to associate public IP as a destination address to the rule using following configuration:

```
    nat_rule_collections = {
      rule1 = {
        name     = "rule1"
        priority = 100
        action   = "Dnat"

        rules = {
          https = {
            name                  = "https"
            source_ip_groups_keys = ["clients"]
            # source_ip_groups = 
            destination_ports                 = ["443"]
            destination_address_public_ip_key = ["pip_key"]
            translated_address                = "10.0.0.1"
            translated_port                   = "443"
            protocols                         = ["TCP"]
          }
        }
      }
```

The deployment of the above code fails due to incorrect type on attribute `destination_address`. As per terraform docs, this attribute should be a `string` whereas it is being returned as an array

Affected code: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/networking/firewall_policy_rule_collection_groups/firewall_policy_rule_collection_groups.tf#L141

```
          destination_address = try(rule.value.destination_address, try(flatten([
            for key, value in var.public_ip_addresses : value.ip_address
            if contains(rule.value.destination_address_public_ip_key, key)
            ]), null)
          )
```

Potential fix

```
          destination_address = try(rule.value.destination_address, try(flatten([
            for key, value in var.public_ip_addresses : value.ip_address
            if contains(rule.value.destination_address_public_ip_key, key)
            ][0]), null)
          )
```

Error log
```
  on /home/vscode/.terraform.cache/modules/solution/modules/networking/firewall_policy_rule_collection_groups/firewall_policy_rule_collection_groups.tf line 144, in resource "azurerm_firewall_policy_rule_collection_group" "polgroup":
 144:           destination_address = try(rule.value.destination_address, try(flatten([
 145:             for key, value in var.public_ip_addresses : value.ip_address
 146:             if contains(rule.value.destination_address_public_ip_key, key)
 147:             ]), null)
 148:           )
```

**Comment by terorform** [comment]
Hi, trying to add a DNAT rule in firewall_policy_rule_collection_groups results in an error:

155: destination_address try(
156: rule.value.desination_address,
157: var.public_ip_address[rule.value.destination_address_publicv_ip_key].ip_address
158:)

rule.value is object with 7 attributes
rule.value.destination_address_public_ip_key is "myPIP" (I checked state in hub and in public IP addresse and the key is there with the public IP)
var.public_ip_addresses is object with no attributes

This object does not have an attribute named "destination_address".
Invalid index (at

The given key does not identify an element in this collection value. 

Any ideas?
