### ISSUE TITLE
VNET Peering failing with 400 Permission Error with MI

### ISSUE THREAD

**Issue by sharmilamusunuru** [aztfmod/terraform-azurerm-caf#1162]
Even after MI has owner privilages VNET Peering failed to create

**Comment by sharmilamusunuru** [comment]
error	18-May-2022 16:26:35	Error: checking for presence of existing Resource: (ResourceId "/subscriptions/3be129f3-744b-43ed-9d25-215b0740fade/resourceGroups/urax-rg-singtel-git-core-ntwk-client-dev-sea-01/providers/Microsoft.Network/virtualNetworks/urax-vnet-singtel-git-core-ntwk-dev-sea-02/virtualNetworkPeerings/ntwk_vnet2_TO_build_vnet1" / Api Version "2021-05-01"): DefaultAzureCredential: failed to acquire a token.
error	18-May-2022 16:26:35	Attempted credentials:
error	18-May-2022 16:26:35		EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
error	18-May-2022 16:26:35		ManagedIdentityCredential: no default identity is assigned to this resource
error	18-May-2022 16:26:35		AzureCLICredential: ERROR: Tenant shouldn't be specified for managed identity account
error	18-May-2022 16:26:35	
error	18-May-2022 16:26:35	
error	18-May-2022 16:26:35	  with module.solution.azapi_resource.virtualNetworkPeerings["ntwk_vnet2_TO_build_vnet1"],
error	18-May-2022 16:26:35	  on /home/vscode/.terraform.cache/singtel-dev/rover_jobs/20220518082038471202006/modules/solution/networking.tf line 216, in resource "azapi_resource" "virtualNetworkPeerings":
error	18-May-2022 16:26:35	 216: resource "azapi_resource" "virtualNetworkPeerings" {
error	18-May-2022 16:26:35	
error	18-May-2022 16:26:35	
error	18-May-2022 16:26:35	Error: checking for presence of existing Resource: (ResourceId "/subscriptions/44e4a5d7-1658-4f1f-85b2-f7fbb0f3c2ba/resourceGroups/urax-rg-singtel-git-core-build-vnet-dev-sea-01/providers/Microsoft.Network/virtualNetworks/urax-vnet-singtel-git-core-build-vnet-dev/virtualNetworkPeerings/build_vnet1_TO_ntwk_vnet2" / Api Version "2021-05-01"): DefaultAzureCredential: failed to acquire a token.
error	18-May-2022 16:26:35	Attempted credentials:
error	18-May-2022 16:26:35		EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
error	18-May-2022 16:26:35		ManagedIdentityCredential: no default identity is assigned to this resource
error	18-May-2022 16:26:35		AzureCLICredential: ERROR: Tenant shouldn't be specified for managed identity account

**Comment by ms-henglu** [comment]
HI @sharmilamusunuru ,

I guess you want to authenticate via a user assigned identity? If so, it's a known issue and just been fixed, but not released yet.
https://github.com/Azure/terraform-provider-azapi/issues/108

**Comment by LaurentLesle** [comment]
yes correct @ms-henglu

**Comment by sharmilamusunuru** [comment]
Hi @ms-henglu  can you please let us know when you are going to publish this change in the latest azapi repo so that we can quickly confirm whether it works or not

**Comment by ms-henglu** [comment]
Hi @sharmilamusunuru , I'll make a release today and will let you know when it's done.

**Comment by ms-henglu** [comment]
Hi @sharmilamusunuru ,

I just released the fix in https://github.com/Azure/terraform-provider-azapi/releases/tag/v0.2.1, would you please give it a try?
