### ISSUE TITLE
Epic - Add multi-subscription support

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#119]
You can propose additional scenario my adding your comment

- [x] Vnet peering between subscriptions
- [x] Private links

**Comment by LaurentLesle** [comment]
https://github.com/aztfmod/terraform-azurerm-caf/tree/master/examples/networking

**Comment by brk3** [comment]
Hi @LaurentLesle, where could I see the example for 'Vnet peering between subscriptions'? I'm not seeing much relevant in the above link? Any pointers would be much appreciated.
