### ISSUE TITLE
Azure AKS Agic

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1195]
To use AKS with Application Gateway integration there are four scenarios described:

- [AKS Add-On Greenfield Deployment](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new) (is not possible to configure)
- [AKS Add-On Brownfield Deployment](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing) (is already possible with aks module)
- ~~Helm Greenfield Deployment~~ (not relevant for terraform deployment)
- ~~Helm Brownfield Deployment~~ (not relevant for terraform deployment)

I will raise a PR to also support Greenfield Deployment with example.

**Comment by arnaudlh** [comment]
Closing as merged for 5.6.0
