### ISSUE TITLE
Unable to create multiple mysql server vnet rules

### ISSUE THREAD

**Issue by reshmarajan1730** [aztfmod/terraform-azurerm-caf#1227]
Right now it does not seems to be possible to create multiple mysql vnet rules with different subnets.

According to the mysql server module, subnet id is not part of the mysql vnet rules loop.
https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/databases/mysql_server/network_rule.tf
So it's only possible to refer a single subnet.

As per example, the mysql_vnet_rules block is using vnet and subnet reference from the top mysql server parameters. 
```
vnet_key = "vnet_region1"
subnet_key = "mysql_subnet"
mysql_vnet_rules = {
  mysql_vnet_rule = {
  name = "mysql-vnet-rule"
  }
}
```
I will raise a pull request in order to create multiple mysql vnet rules with different subnets.

**Comment by arnaudlh** [comment]
thanks @reshmarajan1730, I will assign the issue to you so we can track that you are working on it! 
thanks!
