### ISSUE TITLE
Unable to set timestamp for vm_extension and vmss_extension custom_script

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1231]
It seems there is a bug in both [vm_extension](https://github.com/aztfmod/terraform-azurerm-caf/blob/d0f9bbc0cbf7d18e126970906b54d222ca2c7740/modules/compute/virtual_machine_extensions/custom_script.tf#L13) and [vmss_extension](https://github.com/aztfmod/terraform-azurerm-caf/blob/d0f9bbc0cbf7d18e126970906b54d222ca2c7740/modules/compute/virtual_machine_scale_set_extensions/custom_script.tf#L14) custom_script. There is a function used (toint) which is not existing in terraform, there is only [tonumber](https://www.terraform.io/language/functions/tonumber). The reason why it was not seen before is that try will supress the error.

```
   settings = jsonencode(
     {
-      "fileUris" : local.fileuris,
-      "timestamp" : try(toint(var.extension.timestamp), 12345678)
+      fileUris  = local.fileuris,
+      timestamp = try(tonumber(var.extension.timestamp), 1234568)
     }
   )
```

I will raise a PR to fix this issue.

**Comment by arnaudlh** [comment]
Assigning to you waiting for the PR? ;)
