### ISSUE TITLE
[Feature request] Dynamic Keyvault Certificates

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to have something similar like dynamic key vault secrets for certificates. It should be possible to directly inject certificates or via output from other resources or providers.

### New or Affected Resource(s

azurerm_key_vault_certificate

### Potential Configuration file

```hcl
dynamic_keyvault_certificates = {
  vault = {
    # Self Signed Certificate e.g. created with TLS or ACME Provider
    dynamic_certificate_from_output = {
      secret_name   = "dynamic-certificate-from-output"
      output_key    = "self_signed_certs"
      resource_key  = "self_signed_cert"
      attribute_key = "certificate_bundle_pem"
    }
    dynamic_certificate_plain = {
      secret_name   = "dynamic-certificate-plain"
      contents      = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCB ...."
    }
  }
}
```

**Comment by nusrath432** [comment]
@arnaudlh  @wasfree 
Hi Nick,
I guess we forgot adding this variable 

https://github.com/aztfmod/terraform-azurerm-caf/blob/main/variables.tf#L283

variable "dynamic_keyvault_certificates" {
  default = {}
}

**Comment by nusrath432** [comment]
@wasfree Could you share how you generated the certificate itself because when I tired to import; I see the following error:
The specified PKCS#12 X.509 certificate content can not be read. Please check if certificate is in valid PKCS#12 format.
