### ISSUE TITLE
Bug report-

### ISSUE THREAD

**Issue by sharmilamusunuru** [aztfmod/terraform-azurerm-caf#1276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.5.6

### Rover Version

1.2.1-2206.0903

### Affected Resource(s)/Data Source(s)

azurerm_automation_account

### Terraform Configuration Files

```hcl
We are using this tfvars and it's failing with below error https://github.com/aztfmod/terraform-azurerm-caf/blob/main/examples/automation/101-automation-account-linked/configuration.tfvars

14-Jul-2022 15:40:48	Error: Error in function call
14-Jul-2022 15:40:48	
14-Jul-2022 15:40:48	  on ../aztfmod/automations.tf line 9, in module "automations":
14-Jul-2022 15:40:48	   9:   location            = can(local.global_settings.regions[each.value.region]) ? local.global_settings.regions[each.value.region] : local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group.key, each.value.resource_group_key)].location
```

**Comment by arnaudlh** [comment]
Closing as no details
