### ISSUE TITLE
Bug report - azurerm_application_gateway - Private and public ip_configuration should be optional

### ISSUE THREAD

**Issue by joselcaguilar** [aztfmod/terraform-azurerm-caf#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.0

### Rover Version

NA

### Terraform Version

1.2.6

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
Example 103-public-only which has been fixed for CICD
```

### Expected Behaviour

Run successfully, avoid asking for frontend private subnet_id and cidr. Missing public `http_listener` added to the example 103.

### Actual Behaviour

https://github.com/aztfmod/terraform-azurerm-caf/runs/7644542939?check_suite_focus=true

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by arnaudlh** [comment]
Closing as merged
