### ISSUE TITLE
2 key variables were eliminated mistakenly from virtual_machines_scale_sets.tf on July 18th "lbs" and "lb_backend_address_pool"

### ISSUE THREAD

**Issue by ghazalehca** [aztfmod/terraform-azurerm-caf#1307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

current main

### Terraform Version

1.2.5

### Affected Resource(s)/Data Source(s)

virtual machine scale set linux

### Terraform Configuration Files

```hcl
compute/virtual_machine_scale_set/vmss_linux.tf
```

### Expected Behaviour

in version 5.6.0, vmss_linux.tf had no errors being produced during terraform-apply.

### Actual Behaviour

 Now, getting **invalid-index** error about the variable var.lb_backend_address_pool (line 116) during terraform apply since commit: **cd9fd1e95350d2a5089a7a2a721b711bbe14c97f** by VolkerWessels on July 18th.  var.lb_backend_address_pool is no longer declared

Version 5.6.0 did not have this error reported because the proper variables were declared in virtual_machines_scale_sets.tf

**Comment by hyperfocus1337** [comment]
Sorry for the inconvenience, [PR](https://github.com/aztfmod/terraform-azurerm-caf/pull/1316) with fix submitted.

**Comment by ghazalehca** [comment]
thanks @hyperfocus1337 !  looks good!
