### ISSUE TITLE
Bug report - Tag inheritance is not working for Private Endpoints defined in various modules - Keyvault in specific

### ISSUE THREAD

**Issue by nusrath432** [aztfmod/terraform-azurerm-caf#1319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.1

### Rover Version

aztfmod/rover:1.1.7-2203.2311

### Terraform Version

1.1.7

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoints

### Terraform Configuration Files

```hcl
NA
```

### Expected Behaviour

We should be able to define tags:
- specific to the Private Endpoint [each.value.tags]
- specific to the Resource [e.g. Keyvault] [each.value.tags] 
- Inherited from the Resource Group [global_setttings/custom_variables - current landingzone], if inherit_tags  = true
- Inherited from the Resource Group [global_setttings/custom_variables - remote lower landingzone], if inherit_tags  = true and global_settings_key = <lower-landingzone> if defined.
- Merge all the tags, if tags are defined at all places, specific tag block override global_settings if key with key-value pair coincides.

* base_tags vs tags is bit confusing as base_tags is define within the root_module.tf as well as modules/child_module.tf.

Since, Private Endpoint is used within almost all the modules, maybe we can create a standard design pattern private_endpoints.tf which can be re-used and standardised across modules.

module.tf
```
module "private_endpoint" {
  source   = "../../networking/private_endpoint"
  for_each = lookup(var.settings, "private_endpoints", {})
  base_tags           = try(merge(local.tags, each.value.tags), {})
}
```
main.tf
```
locals {
  module_tag = {
    "module" = basename(abspath(path.module))
  }
  tags = merge(var.base_tags, local.module_tag, try(var.settings.tags, null))
} 
```

root_module.tf
```
base_tags          = try(local.global_settings.inherit_tags, false) ? try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group.key, each.value.resource_group_key)].tags, {}) : {}
```

### Actual Behaviour

When inherit_tags  = true, only Keyvault is inheriting the tags but the Private Endpoint is not inheriting those tags.

**Comment by arnaudlh** [comment]
thanks @nusrath432 for reporting this one, we found it broader than private endpoints. we will be fixing that in the next hotfix release ```5.6.6``` if everything goes according to plans! I've tagged in GH the branch where we integrate the fixes!
