### ISSUE TITLE
Bug report- When setting up an auto-scaled VMSS, load_balancer_backend_address_pool_ids is undefined  

### ISSUE THREAD

**Issue by ghazalehca** [aztfmod/terraform-azurerm-caf#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.1

### Terraform Version

1.2.5

### Affected Resource(s)/Data Source(s)

virtual machine scale set linux - autoscaled

### Terraform Configuration Files

```hcl
terraform-azurerm-caf/modules/compute/virtual_machine_scale_set/vmss_linux.tf
```

## Current Situation

When adding the `autoscaled = true` setting to the `virtual_machine_scale_sets` map in _firewalls.tf_, we are hitting a bug in the caf module that needs to be corrected.  For the time being, we will need to set that value to `false`.  This will direct the code to use the `vmss` resource in the _vmss-linux.tf_ file of the caf module, as opposed to using the `vmss-autoscaled` resource in that same file.  The result is that **the firewalls must be manually scaled**.

## Remediation

In the meantime, we can do one or more of the following
- clone the caf module and add it into our project and fix the problem
- clone the caf module and add it to GNTGitLab, fix the problem, and change the source for our caf module
- fork the caf module in GitHub, fix the problem, submit a pull request

## Bug details

There is no declaration of the value `local.load_balancer_backend_address_pool_ids` which breaks the code.  This is an expected result when the `try()` function references an undeclared object.  This results in a A local value with the name "some_missing_object" has not been declared error.  Please refer to the Terraform [try function documentation](https://www.terraform.io/language/functions/try).

Here is the `vmss_autoscaled` section of _vmss-linux.tf_ in question

```terraform
      ip_configuration {
        name                                         = azurecaf_name.linux_nic[network_interface.key].result
        primary                                      = try(network_interface.value.primary, false)
        subnet_id                                    = can(network_interface.value.subnet_id) ? network_interface.value.subnet_id : var.vnets[try(network_interface.value.lz_key, var.client_config.landingzone_key)][network_interface.value.vnet_key].subnets[network_interface.value.subnet_key].id
        load_balancer_backend_address_pool_ids       = try(local.load_balancer_backend_address_pool_ids, null)
        application_gateway_backend_address_pool_ids = try(local.application_gateway_backend_address_pool_ids, null)
        application_security_group_ids               = try(local.application_security_group_ids, null)
      }
```

Here is the `vmss` section of _vmss-linux.tf_ which works fine

```terraform
      ip_configuration {
        name      = azurecaf_name.linux_nic[network_interface.key].result
        primary   = try(network_interface.value.primary, false)
        subnet_id = can(network_interface.value.subnet_id) ? network_interface.value.subnet_id : var.vnets[try(network_interface.value.lz_key, var.client_config.landingzone_key)][network_interface.value.vnet_key].subnets[network_interface.value.subnet_key].id
        load_balancer_backend_address_pool_ids = can(network_interface.value.load_balancers) ? flatten([
          for lb, lb_value in try(network_interface.value.load_balancers, {}) : [
            can(var.lb_backend_address_pool[try(lb_value.lz_key, var.client_config.landingzone_key)][lb_value.lbap_key].id) ? var.lb_backend_address_pool[try(lb_value.lz_key, var.client_config.landingzone_key)][lb_value.lbap_key].id : var.load_balancers[try(lb_value.lz_key, var.client_config.landingzone_key)][lb_value.lb_key].backend_address_pool_id
          ]
        ]) : []
        application_gateway_backend_address_pool_ids = try(local.application_gateway_backend_address_pool_ids, null)
        application_security_group_ids               = try(local.application_security_group_ids, null)
      }
```

### Actual Behaviour

load_balancer_backend_address_pool_ids  it is reported/logged as undefined during plan/apply.

### Steps to Reproduce

see expected behavior

**Comment by arnaudlh** [comment]
Closing as #1329 been merged and on ramp for 5.6.2
