### ISSUE TITLE
Terraform init fails - child module requires an additional configuration for provider

### ISSUE THREAD

**Issue by hannesbreit** [aztfmod/terraform-azurerm-caf#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.1

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

no specific resource. Init fails.

### Terraform Configuration Files

```hcl
Using the getting started files.
```

### Expected Behaviour

Init should work without any issues.

### Actual Behaviour

I try to init terraform but if fails. The error message is:

Error: Missing required provider configuration
│ 
│   on main.tf line 1:
│    1: module "caf" {
│ 
│ The child module requires an additional configuration for provider
│ hashicorp/azurerm, with the local name "azurerm.vhub".
│ 
│ Refer to the module's documentation to understand the intended purpose of
│ this additional provider configuration, and then add an entry for
│ azurerm.vhub in the "providers" meta-argument in the module block to choose
│ which provider configuration the module should use for that purpose.

### Steps to Reproduce

set up the getting started tutorial and run terraform init

**Comment by arnaudlh** [comment]
Check with the following: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/UPGRADE.md#550

**Comment by arnaudlh** [comment]
Closing as the doc should answer the question, dont hesitate to open/comment if still not able to use.
