### ISSUE TITLE
Bug report- remote kv is not supported in mssql managed instance module

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

support for remote kv is missing in mssql managed instance modules

### Version of the module you are using

main branch

### Rover Version

1.2.3-2207.0210

### AzureRM Provider Version

"~> 2.99"

### Affected Resource(s)/Data Source(s)

mssql_managed_instances, mssql_managed_instances_secondary modules

### Terraform Configuration Files

```hcl
mssql_managed_instances = {
  sqlmi1 = {
    resource_group_key = "cacn_level3_app_rg_01"
    name               = "lz-sql-mi-13"

    sku = {
      name = "GP_Gen5"
    }

    lz_key        = "caf_level2_lob1_security-rg"
    keyvault_key = "cacn_kv_01"

    administratorLogin = "adminuser"
    # administratorLoginPassword = "@dm1nu53r@30102020"
    # if password not set, a random complex passwor will be created and stored in the keyvault
    # the secret value can be changed after the deployment if needed

    //networking
    networking = {
      lz_key      = "caf_level2_vnets_lob1"
      vnet_key   = "cacn_vnet_01"
      subnet_key = "cacn_vnet_01_snet_05"
    }

    storageSizeInGB = 32
    vCores          = 4

    identity = {
      type = "SystemAssigned"
    }
  }
}
```

**Comment by arnaudlh** [comment]
Hi @riteshmehta66, as mentionned by @nusrath432 in the discussion, this is already supported by the 

```
# remote landingzone:
keyvault = {
  key = "<mykv-key>"
  lz_key = "<my-remote-lz-key>"
}
```

Can you please reopen if that syntax does not work?

**Comment by riteshmehta66** [comment]
Hello @arnaudlh : above keyvault syntax worked. Thanks ! Do you want me to update examples for documentation ?

**Comment by riteshmehta66** [comment]
BTW, I am seeing another issue below 3 times now. Kindly let me know if this is known, any workarounds or you believe it is  genuine and you want me to open an issue to track it ?

Is there a reason to use azurerm_template_deployment ? instead of native modules or there is lack of functionality hence used ?

===============================================
module.solution.module.mssql_managed_instances["sqlmi1"].azurerm_template_deployment.mssqlmi: Still creating... [3h20m42s elapsed]
module.solution.module.mssql_managed_instances["sqlmi1"].data.azapi_resource.mssqlmi: Still reading... [3h20m52s elapsed]
module.solution.module.mssql_managed_instances["sqlmi1"].azurerm_template_deployment.mssqlmi: Still creating... [3h20m52s elapsed]
module.solution.module.mssql_managed_instances["sqlmi1"].data.azapi_resource.mssqlmi: Still reading... [3h21m2s elapsed]
module.solution.module.mssql_managed_instances["sqlmi1"].azurerm_template_deployment.mssqlmi: Creation complete after 3h21m1s [id=/subscriptions/85f466ae-558f-471c-b9e8-5be40e40910d/resourceGroups/rg-trl-cacn-lob1-app-rg-created-at-level3-001-sqlmi/providers/Microsoft.Resources/deployments/lz-sql-mi-14]
╷
│ Error: not found "Resource: (ResourceId \"/subscriptions/85f466ae-558f-471c-b9e8-5be40e40910d/resourceGroups/rg-trl-cacn-lob1-app-rg-created-at-level3-001-sqlmi/providers/Microsoft.Sql/managedInstances/lz-sql-mi-14\" / Api Version \"2021-11-01-preview\")": GET https://management.azure.com/subscriptions/85f466ae-558f-471c-b9e8-5be40e40910d/resourceGroups/rg-trl-cacn-lob1-app-rg-created-at-level3-001-sqlmi/providers/Microsoft.Sql/managedInstances/lz-sql-mi-14
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: ResourceNotFound
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "ResourceNotFound",
│     "message": "The Resource 'Microsoft.Sql/managedInstances/lz-sql-mi-14' under resource group 'rg-trl-cacn-lob1-app-rg-created-at-level3-001-sqlmi' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.solution.module.mssql_managed_instances["sqlmi1"].data.azapi_resource.mssqlmi,
│   on ../../dev-modules/modules/databases/mssql_managed_instance/managed_instance.tf line 109, in data "azapi_resource" "mssqlmi":
│  109: data "azapi_resource" "mssqlmi" {
│ 
╵
Terraform apply return code: 1
