### ISSUE TITLE
Bug report- Bug report- remote kv is not supported in mssql_servers module

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#1364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Adding support for remote kv

### Version of the module you are using

Master branch

### Rover Version

1.2.3-2207.0210

### AzureRM Provider Version

"~> 2.99"

### Affected Resource(s)/Data Source(s)

mssql_servers module

### Terraform Configuration Files

```hcl
mssql_servers = {
  sales-rg1 = {
    name                = "sales-rg1"
    region              = "region1"
    resource_group_key  = "cacn_level3_app_rg_01"
    version             = "12.0"
    # Generate a random password and store it in keyvaul secret
    lz_key                        = "caf_level3_lob1_security-rg"
    keyvault_key                  = "cacn_kv_01"
    # keyvault_key                  = "sql-rg1"
    administrator_login = "sqlsalesadmin"
    
    connection_policy             = "Default"
    system_msi                    = true
    public_network_access_enabled = false


    tags = {
      segment = "sales"
    }

    # Optional
    private_endpoints = {
      # Require enforce_private_link_endpoint_network_policies set to true on the subnet
      private-link-level4 = {
        name       = "sales-sql-rg1"
        lz_key     = "caf_level2_vnets_lob1" 
        vnet_key   = "cacn_vnet_01"
        subnet_key = "cacn_vnet_01_snet_03"
        #subnet_id          = "/subscriptions/97958dac-f75b-4ee3-9a07-9f436fa73bd4/resourceGroups/ppga-rg-sql-rg1/providers/Microsoft.Network/virtualNetworks/ppga-vnet-testvnet1/subnets/ppga-snet-web-subnet"
        resource_group_key = "cacn_level3_app_rg_01"

        private_service_connection = {
          name                 = "sales-sql-rg1"
          is_manual_connection = false
          subresource_names    = ["sqlServer"]
        }

        # private_dns = {
        #   zone_group_name = "privatelink_database_windows_net"
        #   # lz_key          = ""   # If the DNS keys are deployed in a remote landingzone
        #   keys = ["privatelink"]
        # }
      }
    }
  }
}
```

**Comment by nusrath432** [comment]
@riteshmehta66 Can you try the block as follows:
```
keyvault = {
  key = "<mykv-key>"
  lz_key = "<my-remote-lz-key>"
}
```
Also, mention the CAF version you are using - current one is 5.6.1

**Comment by riteshmehta66** [comment]
Hello @nusrath432 : Yes, as per your suggestion below syntax has worked. Do you want me to update examples section ?

keyvault = {
  key = "<mykv-key>"
  lz_key = "<my-remote-lz-key>"
}

**Comment by nusrath432** [comment]
@riteshmehta66  if it is missing, yes please. Thanks

**Comment by riteshmehta66** [comment]
works with

keyvault = {
key = ""
lz_key = ""
}
