### ISSUE TITLE
Reference a central boot diagnostic storage account for vms

### ISSUE THREAD

**Issue by florian-ried** [aztfmod/terraform-azurerm-caf#1394]
I'm just facing the same question. How do I reference a central boot diagnostic storage account that is in a different landing zone for multiple VMs? I've tried the following, but unfortunately without success.

![image](https://user-images.githubusercontent.com/95634472/195865279-c2c99fb6-ed23-4659-b786-29ef33cf38e6.png)

_Originally posted by @florian-ried in https://github.com/aztfmod/terraform-azurerm-caf/issues/938#issuecomment-1279048482_

**Comment by jikuja** [comment]
Do you have some special use case to use storage account for boot diagnostics?

Managed boot diagnostics storage account is the recommended option: https://learn.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#boot-diagnostics-storage-account

On API-level: https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#bootdiagnostics
