### ISSUE TITLE
Add Azure Login Extension for virtual machines

### ISSUE THREAD

**Issue by schoenr79** [aztfmod/terraform-azurerm-caf#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

create the AADLoginExtension for VM's

### New or Affected Resource(s

azurerm_virtual_machine_extension

**Comment by arnaudlh** [comment]
hi @schoenr79 this feature should be available with the "generic extension" capability we added,  as exhibited in here: 
https://github.com/aztfmod/terraform-azurerm-caf/blob/56c322ba4758824de049992de9b855af96259206/examples/compute/virtual_machine/214-vm-generic_extensions_complex/configurations.tfvars#L46

Please reopen the issue if not working :)
