### ISSUE TITLE
Bug report-sql mi deployment error

### ISSUE THREAD

**Issue by amadkamal** [aztfmod/terraform-azurerm-caf#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

int-5.6.0

### Affected Resource(s)/Data Source(s)

mssql_managed_instances

### Terraform Configuration Files

```hcl
mssql_managed_instances = {
  sqlmi01 = {
    resource_group_key = ""
    name               = "sqlmi04"
    sku = {
      name = "GP_Gen5"
      edition = "GeneralPurpose"
    }

    administratorLogin         = ""
    keyvault_key               = ""

    //networking
    networking = {
      lz_key     = "networking_spoke_sqlmi"
      vnet_key   = "sqlmi_region1"
      subnet_key = "sqlmi2"
    }

    vCores          = 16
    storageSizeInGB = 2048

    publicDataEndpointEnabled = false
    minimalTlsVersion         = "1.2"
    collation                 = "SQL_Latin1_General_CP1_CI_AS"
    storageAccountType        = "ZRS"
    licenseType               = "BasePrice"
  }
}
```

### Expected Behaviour

the sql mi created successfully

### Actual Behaviour

the module return error on 1st apply attempt. only succeed on 2nd apply attempt.
potential root cause of this issue is on dependency resource creation.

##[error]Bash exited with code '1'.
##[error]Bash wrote one or more lines to the standard error stream.
##[error]╷
│ Error: not found "Resource: (ResourceId \"/subscriptions/xxx/resourceGroups/xxx-rg/providers/Microsoft.Sql/managedInstances/sqlmi04\" / Api Version \"2021-11-01-preview\")": GET https://management.azure.com/subscriptions/xxx/resourceGroups/xxx-rg/providers/Microsoft.Sql/managedInstances/sqlmi04
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: ResourceNotFound
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "ResourceNotFound",
│     "message": "The Resource 'Microsoft.Sql/managedInstances/sqlmi04' under resource group 'xxx-rg' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"](https://aka.ms/ARMResourceNotFoundFix%22)
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.solution.module.mssql_managed_instances["sqlmi04"].data.azapi_resource.mssqlmi,
│   on ../aztfmod/modules/databases/mssql_managed_instance/managed_instance.tf line 109, in data "azapi_resource" "mssqlmi":
│  109: data "azapi_resource" "mssqlmi" {
│

**Comment by BerendvW** [comment]
@amadkamal you left the value for  `resource_group_key` empty on purpose I assume?

**Comment by LaurentLesle** [comment]
This issue addresses the warnings in azurerm 2.99.0 related to the deprecation of azurerm_template_deployment and is now replaced with azurerm_resource_group_template_deployment
Most of the impacted resources where related to the original implementation and have now a native provider support in azurerm.

NOTE : Terraform with destroy the azurerm_template_deployment deployment. Destroying the azurerm_template_deployment DOES NOT DELETE the resources that were deployed part of the arm template.
This PR will replace them by azurerm_resource_group_template_deployment using the same ARM template using an incremental mode. This redeployment will NOT IMPACT existing resources.

NOTE: The new behaviour of azurerm_resource_group_template_deployment with the azurerm provider will destroy the nested resources and resource part of the ARM template deployment when running the Terraform DESTROY. For that reason the null-resources that were in change of the destroy are now removed. It will be shown in the plan as being destroyed but as they are not anymore in the code, they will be just removed from the state.
