### ISSUE TITLE
Using existing Group?

### ISSUE THREAD

**Issue by kbk574** [aztfmod/terraform-azurerm-caf#1412]
Hello brilliant aztfmod creators!

I am wondering if I could use this to reference an existing AAD group instead of creating a new one. Is that something possible, and simply escaping my mind how to accomplish?

https://github.com/aztfmod/terraform-azurerm-caf/blob/6cf965a9310cb1fe2108ff73e49c92ae46322993/examples/azuread/201-groups-and-roles/configuration.tfvars#L86

Please advise!

Khalid

**Comment by arnaudlh** [comment]
hi @kbk574, yes at rbac composition time ```role_mapping=```, you should be able to add an existing group: ```object_ids = {...}``` as exhibited here: https://github.com/aztfmod/terraform-azurerm-caf/blob/c05e2f4da3df03257db4531ee4d165f2613f7103/examples/compute/azure_redhat_openshift/101_basic_private_cluster/principal.tfvars#L81

**Comment by kbk574** [comment]
Thank you @arnaudlh. I searched but apparently missed this example. Royally appreciated!
