### ISSUE TITLE
Feature request- CAF Terraform Module for Private DNS Resolver

### ISSUE THREAD

**Issue by sharmilamusunuru** [aztfmod/terraform-azurerm-caf#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I can see currently hashicorp is in process of releasing the module for private DNS resolver looking forward to add that feature into CAF.

### New or Affected Resource(s

azurerm_private_resolver

**Comment by LaurentLesle** [comment]
Closing as merged and will be part of 5.7.0
