### ISSUE TITLE
Feature request-Allow `destination_fqdns` in network rules of Firewall Policy

### ISSUE THREAD

**Issue by sponte** [aztfmod/terraform-azurerm-caf#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Firewall policy allows users to use FQDNs in the network rules - this is currently not available in the CAF module

### New or Affected Resource(s

azurerm_firewall_network_rule_collection

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_network_rule_collection#destination_fqdns

**Comment by LaurentLesle** [comment]
Closing as merged
