### ISSUE TITLE
Bug report-`proxy` is deprecated and will be renamed to `gateway` in version 3.0 of the AzureRM provider

### ISSUE THREAD

**Issue by kevintrannz** [aztfmod/terraform-azurerm-caf#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.5

### Affected Resource(s)/Data Source(s)

azurerm_api_management_custom_domain

### Terraform Configuration Files

```hcl
module "caf" {
  source  = "aztfmod/caf/azurerm"
  version = "5.6.5"

  providers = {
    azurerm.vhub = azurerm.vhub
  }

  # insert the 7 required variables here
  global_settings = {
    default_region = "region1"

    regions = {
      region1 = var.deployment_region
    }
  }

...
```

### Expected Behaviour

no warning or error

### Actual Behaviour

 Warning: Argument is deprecated
│ 
│   with module.caf.module.api_management_custom_domain.azurerm_api_management_custom_domain.apim,
│   on .terraform/modules/caf/modules/apim/api_management_custom_domain/module.tf line 1, in resource "azurerm_api_management_custom_domain" "apim":
│    1: resource "azurerm_api_management_custom_domain" "apim" {
│ 
│ `proxy` is deprecated and will be renamed to `gateway` in version 3.0 of the AzureRM provider

### Steps to Reproduce

terraform plan

**Comment by arnaudlh** [comment]
could not find an easy to make it go away in 2.99, If you find a fix for this @kevintrannz, happy to take a PR. 
but will be fixed in 5.7.0 which will be in azurerm > 3.45

**Comment by kevintrannz** [comment]
Hi @arnaudlh,
No. I do not have a fix for this. Do you know when 5.7 released please ?

**Comment by LaurentLesle** [comment]
We are waiting for a stable build and address all those issues before releasing it. This is top of mind as the moment.

**Comment by LaurentLesle** [comment]
closing as duplicate #1317
