### ISSUE TITLE
Shared image gallery add option for hyper_v_generation in shared image gallery

### ISSUE THREAD

**Issue by joeybdub** [aztfmod/terraform-azurerm-caf#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adding variable option for v2 generation in PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/1535

### New or Affected Resource(s

azurerm_shared_image

### Potential Configuration file

```hcl
Image_definitions.tf
resource "azurecaf_name" "image_name" {
  name          = var.settings.name
  prefixes      = var.global_settings.prefixes
  resource_type = "azurerm_shared_image"
  random_length = var.global_settings.random_length
  clean_input   = true
  passthrough   = var.global_settings.passthrough
  use_slug      = var.global_settings.use_slug
}

resource "azurerm_shared_image" "image" {
  name                = azurecaf_name.image_name.result
  gallery_name        = var.gallery_name
  resource_group_name = var.resource_group_name
  location            = var.location
  os_type             = var.settings.os_type
  hyper_v_generation  = var.hyper_v_generation
  identifier {
    publisher = var.settings.publisher
    offer     = var.settings.offer
    sku       = var.settings.sku
  }

}
```

### References

https://github.com/aztfmod/terraform-azurerm-caf/pull/1535 

Add variable for hypervisor v2 option in shared image gallery

**Comment by arnaudlh** [comment]
Closing as merged! Thanks @joeybdub!
