### ISSUE TITLE
Feature request- role mapping support for route tables

### ISSUE THREAD

**Issue by najeebvv** [aztfmod/terraform-azurerm-caf#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

We have an implementation of AKS where it makes use user managed identity and route tables. In order to ensure only necessary privilege is provided to MI, we would like to have the possibility of role assignment with route tables.

### New or Affected Resource(s

azurerm_role_assignment

### Potential Configuration file

```hcl
role_mapping = {
  built_in_role_mapping = {
    route_tables = {      
      route_table1 = {
        "Network Contributor" = {
          managed_identities = {
            keys = ["aks_identity"]
          }
        }
      }
    }
  }
}
```

**Comment by najeebvv** [comment]
[PR](https://github.com/aztfmod/terraform-azurerm-caf/pull/1546)

**Comment by arnaudlh** [comment]
Closing as merged! thanks @najeebvv!
