### ISSUE TITLE
Feature request- Support additional private endpoint for aks apiserver

### ISSUE THREAD

**Issue by najvv** [aztfmod/terraform-azurerm-caf#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

in AKS private cluster scenario, it will be useful if we could create additional private endpoint for aks api endpoint. this removes the necessity of vnet peering between aks and devops agent vnet. Setup is described in MS documentation.

https://learn.microsoft.com/en-us/azure/aks/private-clusters#use-a-private-endpoint-connection

### New or Affected Resource(s

azurerm_private_endpoint

### Potential Configuration file

```hcl
# new private_endpoints block in aks

   private_endpoints = {
      pe1 = {
        name               = "aks-pe"
        #lz_key             = "" # for vnets created in different lz
        vnet_key           = "spoke_aks_re1"
        subnet_key         = "private_endpoints"
        private_service_connection = {
          name                 = "aks-psc"
          is_manual_connection = false
          subresource_names    = ["management"]
        }
      }
    }
```
```


### References

_No response_

**Comment by LaurentLesle** [comment]
closing as merged
