### ISSUE TITLE
Bug report- subscriptions fail to get tags

### ISSUE THREAD

**Issue by MarcelHeek** [aztfmod/terraform-azurerm-caf#1565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.5.5

### Rover Version

aztfmod/rover:1.3.4-2211.2307

### Affected Resource(s)/Data Source(s)

azurerm_subscription

### Terraform Configuration Files

```hcl
N/A
```

### Expected Behaviour

I would expect that the (global) tags defined for the configuration would be applied to the subscription created

### Actual Behaviour

No tags were created

### Steps to Reproduce

N/A

**Comment by LaurentLesle** [comment]
Closing as merged.
