### ISSUE TITLE
Support Key Vault key rotation_policy

### ISSUE THREAD

**Issue by kamilzzz** [aztfmod/terraform-azurerm-caf#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Key Vault keys support autorotation and I would like to be able to configure autorotation using this module.
Support for rotation_policy is already implemented in the azurerm Terraform provider - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key#rotation_policy

### New or Affected Resource(s

azurerm_key_vault_key

### Potential Configuration file

```hcl
resource "azurerm_key_vault_key" "key" {
  name         = var.settings.name
  key_vault_id = var.keyvault.id
  key_type     = var.settings.key_type
  key_opts     = var.settings.key_opts

  key_size        = try(var.settings.key_size, null)
  curve           = try(var.settings.curve, null)
  not_before_date = try(var.settings.not_before_date, null)
  expiration_date = try(var.settings.expiration_date, null)

  **rotation_policy = try(var.settings.rotation_policy, null)**

  tags            = local.tags
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key#rotation_policy

**Comment by LaurentLesle** [comment]
Added part of SQL mi native azurerm support in 5.7.0.
Closing.
