### ISSUE TITLE
Application gateway diagnostic settings for log analytics workspace

### ISSUE THREAD

**Issue by adnansk121** [aztfmod/terraform-azurerm-caf#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.4

### Rover Version

aztfmod/rover:1.3.1-2210.0303

### Affected Resource(s)/Data Source(s)

azurerm_applicaitongateway

### Terraform Configuration Files

```hcl
diagnostic_profiles = {
      operations = {
        name             = "agwoperations"
        definition_key   = "log_analytics"
        destination_type = "log_analytics"
        destination_key  = "central_logs"
      }
    }
```

### Expected Behaviour

The diagnostic definitions should be referred from lower level i.e. level 2 in my case and diagnostic settings should be configured. 

### Actual Behaviour

when I give diagnostics definitions and log analytics.tfvars in the same level it works but when referring to lower level the block is ignored

### Steps to Reproduce

create shared services in lower level and add diagnostic definitions in it. try to point to diagnostic settings from current level.

### Important Factoids

no

### References

diagnostic settings for lower level

**Comment by LaurentLesle** [comment]
diagnostic_profiles is using the diagnostics objects from your var.landingzone.global_setting_key (can be a tfstate from the same or lower level). You can check the outputs values in the tfstate to confirm you have the diagnostics objects. The diagnostic definition can be setup in your local deployment (e.g application gateway) and use the destination_type and destination_key from the diagnostics objects.
 
It is red from that key and re-injected in the output variable of your tfstate.
This is why there is no level involved in the diagnostics profiles.

Another approach you should consider for diagnostics profiles is using the enterprise-scale registry module a sister project that can help you creating a management group structure and assign a policy that will setup for you the diagnostic profiles. If you use that approach you don't need to use the diagnostic_profiles in aztfmod caf. The only use cases are when you want to sent the diagnostics to a storage account, a queue or a partner solution as the enterprise scale module only support out of the box the log_analytics workspace.

I am going to close this issue. Re-open is not clear.

**Comment by adnansk121** [comment]
Could you please explain how and which level you the worspace is deployed and how do you refer it? example I tried to give definitions in the same resource file and pointed to destinations in lower level and it doesnt seems to work.

**Comment by bizimunda** [comment]
Yes I am having the same issue.
I have deployed the **workspace** at the **level 0** and the AKS at the **level 3**. And now I want to send all diagnostic logs from AKS (level 3) to workspace (level 0).
![image](https://user-images.githubusercontent.com/4592670/236426415-574356c5-ba67-4fd8-a029-e06a7e073a70.png)
here is my level 0 where I have defined the workspace in the launchpad folder.
```
diagnostic_log_analytics = {
  central_logs_region1 = {
    region             = "region1"
    name               = "logs"
    resource_group_key = "monitoring"
  }
}
```

![image](https://user-images.githubusercontent.com/4592670/236426347-85dfd362-fe46-4656-b79a-2a378ca31c8c.png)

And here is my AKS at the level 3 where I have defined the AKS.

here is my AKS code

```
    log_analytics = {
      central_logs = {
        log_analytics_key              = "central_logs_region1"
        log_analytics_destination_type = "Dedicated"
        log_analytics_resource_id      = "/subscriptions/-----------/resourcegroups/cafap-rg-monitoring-fcg/providers/microsoft.operationalinsights/workspaces/cafap-log-logs-tji"
        log_analytics_workspace_id     = "-------------f"
      }
    }
```
and here is my code of my **landing zone** where I have defined the state file of my level0-->launchpad to reference my **workspace**

```
landingzone = {
  backend_type        = "azurerm"
  level               = "level3"
  key                 = "key_aks"
  global_settings_key = "connectivity_vNet_non_prod"
  tfstates = {
    connectivity_vNet_non_prod = {
      tfstate   = "connectivity_vNet_non_prod.tfstate"
      workspace = "tfstate"
      level     = "lower"
    }
  }
  tfstates = {
    launchpad = {
      tfstate   = "caf_launchpad.tfstate"
      workspace = "tfstate"
      level     = "lower"
    }
  }
}
```
