### ISSUE TITLE
Bug report - API Management without tag defined cause error

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#1585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

There is an issue in API Management tags definition, this should be changed:

**See:** https://github.com/aztfmod/terraform-azurerm-caf/blob/958655d4cc90eddf3c384d3073c15264eed14a2e/modules/apim/api_management/module.tf#L216
**Change From:** tags = merge(local.tags, var.settings.tags, {})
**Change To:** merge(local.tags, try(var.settings.tags, {}))

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.8

### Terraform Version

1.4.5

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
Use Basic Apim test without tags definition e.g.

api_management = {
  apim1 = {
    name   = "example-apim"
    region = "region1"
    resource_group = {
      key = "rg1"
    }
    publisher_name  = "My Company"
    publisher_email = "company@terraform.io"

    sku_name = "Developer_1"
    #tags = {
    #  project = "demo"
    #}
  }
}
```

### Expected Behaviour

No error.

### Actual Behaviour

2023/04/25 13:27:28 
2023/04/25 13:27:28 Error: Unsupported attribute
2023/04/25 13:27:28 
2023/04/25 13:27:28   on /home/AzDevOps_azpcontainer/.terraform/modules/azure/modules/apim/api_management/module.tf line 216, in resource "azurerm_api_management" "apim":
2023/04/25 13:27:28  216:   tags = merge(local.tags, var.settings.tags, {})
2023/04/25 13:27:28     ├────────────────
2023/04/25 13:27:28     │ var.settings is object with 7 attributes
2023/04/25 13:27:28 
2023/04/25 13:27:28 This object does not have an attribute named "tags".

### Steps to Reproduce

Create API Management without tags defined.

### References

https://github.com/aztfmod/terraform-azurerm-caf/blob/958655d4cc90eddf3c384d3073c15264eed14a2e/modules/apim/api_management/module.tf#L216

**Comment by LaurentLesle** [comment]
Good catch. I presume you will submit a PR?
