### ISSUE TITLE
Module Issue For Pass a File in Custom data

### ISSUE THREAD

**Issue by madhulikasarangam** [aztfmod/terraform-azurerm-caf#1619]
Hi Laurent,

As discussed in email, please arrange someone to fix the module issue for below points.

1.	Pass the commands directly in custom data (working for windows not working for Linux)
2.	Create a separate file and pass that file in custom data (not working for both windows and Linux)

**Comment by sharmilamusunuru** [comment]
This Issue has the example referencing to PR https://github.com/aztfmod/terraform-azurerm-caf/pull/1623
