### ISSUE TITLE
Bug : Application GateWay WAF exclusion problem

### ISSUE THREAD

**Issue by gevraud-cicd** [aztfmod/terraform-azurerm-caf#1662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.6.10

### Rover Version

aztfmod/rover:1.4.6-2305.1701

### Affected Resource(s)/Data Source(s)

Application gateway WAF

### Terraform Configuration Files

```hcl
   managed_rules = {
      exclusion = {
        ex1 = {
          match_variable          = "RequestCookieNames"
          selector                = "mysuperword"
          selector_match_operator = "StartsWith"
        }
      }
      managed_rule_set = {
        mrs1 = {
          type    = "OWASP"
          version = "3.2"
          rule_group_override = {
            rgo1 = {
              rule_group_name = "xxx-yyy"
              disabled_rules = [
                "xxx",
                "yyy"
              ]
            }
          }
        }
      }
    }
```

### Expected Behaviour

I expected the module to create it

### Actual Behaviour

It just ignores the code

### Steps to Reproduce

- create an application gateway
- activate the waf
- create a waf policy
- create a managed_rules with an exclusion

**Comment by arnaudlh** [comment]
Closing as merged in main for 5.7.1!
