### ISSUE TITLE
Error: Error in function call │ │   on .terraform\modules\caf\locals.tf line 208, in locals: │  208:   object_id = coalesce(var.logged_user_objectId, var.logged_aad_app_objectId, try(data.azurerm_client_config.current.object_id, null), try(data.azuread_service_principal.logged_in_app.0.object_id, null)) │     ├──────────────── │     │ while calling coalesce(vals...) │     │ data.azuread_service_principal.logged_in_app is empty tuple │     │ data.azurerm_client_config.current.object_id is "" │     │ var.logged_aad_app_objectId is null │     │ var.logged_user_objectId is null │ │ Call to function "coalesce" failed: no non-null, non-empty-string arguments.Bug report-

### ISSUE THREAD

**Issue by Herminder39** [aztfmod/terraform-azurerm-caf#1665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.3.11

### Rover Version

aztfmod/rover:1.4.6-2306.1405

### Terraform Version

v1.4.6

### AzureRM Provider Version

hashicorp/azurerm v2.55.0

### Affected Resource(s)/Data Source(s)

data.azuread_service_principal.logged_in_app is empty tuple

### Terraform Configuration Files

```hcl
Error: Error in function call
│
│   on .terraform\modules\caf\locals.tf line 207, in locals:
│  207:   object_id = coalesce(var.logged_user_objectId, var.logged_aad_app_objectId, try(data.azurerm_client_config.current.object_id, null), try(data.azuread_service_principal.logged_in_app.0.object_id, null))
│     ├────────────────
│     │ while calling coalesce(vals...)
│     │ data.azuread_service_principal.logged_in_app is empty tuple
│     │ data.azurerm_client_config.current.object_id is ""
│     │ var.logged_aad_app_objectId is null
│     │ var.logged_user_objectId is null
│
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

**Comment by arnaudlh** [comment]
Closing as should be resolved in version ```5.7.0```, dont hesitate to repoen if not working.
