### ISSUE TITLE
Feature request-Create Azure Maps Accounts module

### ISSUE THREAD

**Issue by khaman-pet** [aztfmod/terraform-azurerm-caf#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request to create Azure Maps Accounts module. 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account 

### New or Affected Resource(s

azurerm_maps_account

### Potential Configuration file

```hcl
maps_accounts = {
 account1 = {
   name = "name"
   resource_group_key = "rg_key"
   sku = "G2" # S0, S1, G2

  }
}
# Keyvault to store the API Key, unique identifier
# Storage container for the datastore
```

**Comment by arnaudlh** [comment]
hi @khaman-pet, are you thinking about submitting a PR for this one or shall we put it on backlog?

**Comment by khaman-pet** [comment]
@arnaudlh please put it in the backlog

**Comment by reshmarajan1730** [comment]
@arnaudlh could you please assign this to me, I have a PR

**Comment by arnaudlh** [comment]
> @arnaudlh could you please assign this to me, I have a PR

Awesome! Thanks @reshmarajan1730  Looking forward to reviewing it!

**Comment by khaman-pet** [comment]
@arnaudlh @reshmarajan1730 . We are testing the module and facing this issue:
```
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "maps_accounts" but a value was
│ found in the file
│ "/__w/21/s/configuration/level3/map_accounts/maps_accounts.tfvars". If you
│ meant to use this value, add a "variable" block to the configuration.
```

Should we raise the issue here in the https://github.com/Azure/caf-terraform-landingzones repo?

**Comment by reshmarajan1730** [comment]
@khaman-pet , I am unable to replicate this error, standalone test worked for me as did before. Could you please share more details on how you are testing this ?
