### ISSUE TITLE
Azure Security Center Continuous Export 

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#181]
Kindly incorporate capability to enable Azure Security Center's continuous export configurations and point them to supported diagnostic element - event hub, log analytics etc.

**Comment by arnaudlh** [comment]
As part of revamp of ASC coverage, this one is for https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_automation

**Comment by benhurjoel** [comment]
To support the type of Azure Resources to export the data to:

- [ ] EventHub
- [ ] LogAnalytics Workspace
- [ ] LogicApp

**Comment by benhurjoel** [comment]
An Issue raised at the provider's page : https://github.com/terraform-providers/terraform-provider-azurerm/issues/9975

**Comment by benhurjoel** [comment]
Archiving this issue due to low priority requirement.
