### ISSUE TITLE
Bug report-AGW backend settings configuration path and rewrite rule space bug

### ISSUE THREAD

**Issue by Najmi96** [aztfmod/terraform-azurerm-caf#2003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Version of the module you are using

5.7.11

### Rover Version

aztfmod/rover:1.4.6-2306.1405

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
# backend settings configuration
    http_settings = {
      test_https_443 = {
        name                        = "test_https_443"
        front_end_port_key          = "443"
        protocol                    = "Https"
        # host_name                   = "test.agw.com"
        probe_key                   = "test_https_443"
        host_name_from_backend_pool = true
        timeout                     = 30
        path                        = "/*"
      }

rewrite_rule_sets = {
      rrs1 = {
        name = "test_rewrite_rule_set"
      }
    }

    rewrite_rules = {
      rr1 = {
        name                 = "test_rr"
        rewrite_rule_set_key = "rrs1"
        request_headers      = "Content-Type=application/json"
        sequence             = "1"
      }
      content-security-policy_set = {
        name                 = "content-security-policy_set"
        rewrite_rule_set_key = "rrs1"
        response_headers     = "Content-Security-Policy=upgrade-insecure-requests, base-uri=self, frame-ancestors=self, form-action=self, object-src=none"
        sequence             = 163
      }

      permission-policy_set = {
        name                 = "permission-policy_set"
        rewrite_rule_set_key = "rrs1"
        response_headers     = "Permissions-Policy=accelerometer=(self), camera=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), payment=(self), usb=(self)"
        sequence             = 164
      }
    }
```

### Expected Behaviour

In Azure portal backend settings configuration, can use path "/*" but in terraform can only use "/". For rewrite rules seems like terraform does not support spaces while in Azure portal it supports.

### Actual Behaviour

Terraform should support path "/*" for backend settings configuration and should support spaces for rewrite rules.

### Steps to Reproduce

Please include path "/*" in backend settings configuration:

# backend settings configuration
    http_settings = {
      test_https_443 = {
        name                        = "test_https_443"
        front_end_port_key          = "443"
        protocol                    = "Https"
        # host_name                   = "test.agw.com"
        probe_key                   = "test_https_443"
        host_name_from_backend_pool = true
        timeout                     = 30
        path                        = "/*"
      }

For rewrite rules, please put spaces as below:

permission-policy_set = {
        name                 = "permission-policy_set"
        rewrite_rule_set_key = "rrs1"
        response_headers     = "Permissions-Policy=accelerometer=(self), camera=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), payment=(self), usb=(self)"
        sequence             = 164
      }
    }

No issue with plan and apply. Just that the output is wrong

**Comment by onlyillusion** [comment]
Hi @Najmi96 ,
what type of application gateway are you using?v1 or v2?
