### ISSUE TITLE
Epic - APIM

### ISSUE THREAD

**Issue by hieumoscow** [aztfmod/terraform-azurerm-caf#205]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management

- [x] 100 simple APIM
- [x] NSG
- [ ] Hub & Spoke
- [ ] Additional_locations, support regions
- [ ] Diagnostics
- [ ] Managed Identity
- [ ] OAuth2 AAD
- [ ] Azure Key Vault Cert link

**Comment by arnaudlh** [comment]
Closing as tracked under #644
