### ISSUE TITLE
Initial support for Virtual Desktop (WVD).

### ISSUE THREAD

**Issue by abhilash-keloth** [aztfmod/terraform-azurerm-caf#212]
Initial support to include:
- [ ] Application Group
- [ ] Workspace
- [ ] Host pool
- [ ] Session hosts

**Comment by jleonelion** [comment]
@abhilash-keloth For this effort, are you focused on adding support for just the azurerm_virtual_desktop_workspace type or are you considering a more encompassing module that creates a host pool, app group, VMs, etc. (similar to all the resources created by the Marketplace app - "Create Windows Virtual Desktop - Provision a host pool")?

I started stubbing out a module to provision a WVD host pool myself and am happy to contribute.

**Comment by abhilash-keloth** [comment]
@jleonelion : Planning for all the examples including host pools and app group. I already have few in my branch akeloth-vdi. I am trying to add VMs to the host pool and it's bit tricky with extensions. Please share if you have anything in place for the same.

**Comment by jleonelion** [comment]
@abhilash-keloth Thanks for pointing out the branch.  I took a look at your additions. I did a little cleanup, but overall it like you've added these resource types to the module.  If I understand the design pattern here, next step would be to create vm_extensions types for Microsoft.Powershell.DSC and Microsoft.Compute.JsonADDomainExtension.  Then we put it all together in a landingzone example (which would go in a different GitHub project).  Is this your understanding?

**Comment by abhilash-keloth** [comment]
> @abhilash-keloth Thanks for pointing out the branch. I took a look at your additions. I did a little cleanup, but overall it like you've added these resource types to the module. If I understand the design pattern here, next step would be to create vm_extensions types for Microsoft.Powershell.DSC and Microsoft.Compute.JsonADDomainExtension. Then we put it all together in a landingzone example (which would go in a different GitHub project). Is this your understanding?

@jleonelion : yes, both extensions for Domainjoin and session host are completed in my environment. It's pushed to my branch as well. We are in the midst of redesigning or finalizing the way to implement extensions.
