### ISSUE TITLE
Features - Initial implementation of Azure NetApp File

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#226]
Initial implementation of Azure NetApp Files:

- [ ] azurerm_netapp_account
- [ ] azurerm_netapp_pool
- [ ] azurerm_netapp_snapshot
- [ ] azurerm_netapp_volume

**Comment by xpillons** [comment]
@arnaudlh there is a need for additional CAF random names for netapp account, pools and volume. Here are the rules to follow :

 - Account must be unique for the subscription.
 - Capacity pool name must be unique for each NetApp account
 - A volume name must be unique within each capacity pool. It must be at least three characters long. You can use any alphanumeric characters.
