### ISSUE TITLE
Module forces prefix, doesnt support suffix

### ISSUE THREAD

**Issue by AlexBevan** [aztfmod/terraform-azurerm-caf#274]
Created the following PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/273

From my (limited) understanding of [the CAF naming docs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming) suffix is preferred over prefix, current module doesn't support suffix and enforces prefix that does not look to be recommended

**Comment by AlexBevan** [comment]
Looks like #273 got merged, but then didn't? Would you like me to recommit these changes as there has been some code drift since the initial PR?

**Comment by LaurentLesle** [comment]
Closing the issue as now part of the module through
var.global_settings.suffix

**Comment by niksheridan-ops** [comment]
@bnchou I too am having difficultly finding this is in master - did you uncover this in the end?

**Comment by bnchou** [comment]
@niksheridan-ops I've created a new branch on my [fork](https://github.com/bnchou/terraform-azurerm-caf/tree/naming-add-suffix) to resolve that
