### ISSUE TITLE
Enhance synapse to support defining multiple workspace_firewall

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/terraform-azurerm-caf#281]
Current implementation of aztfmod/caf/azurerm//modules/analytics/synapse only supports creating a single workspace_firewall rule.  Request is to expand it to support defining multiple firewall rules.

Example:
```
settings = {
  ...
  workspace_firewalls = {
    rule1 = {
      name = "rule-whatever"
      start_ip = "10.0.0.1"
      end_ip = "10.0.100.0"
    }
  }
}
```

**Comment by jleonelion** [comment]
assign to me and I can add

**Comment by jleonelion** [comment]
@arnaudlh I have the changes made, but cannot commit them.  I am running on Window 10 + VS Code, WSL, Docker using Rover as remote container, but get the below error about python3.6 when I perform commit
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
/usr/bin/env: ‘python3.6’: No such file or directory
```

**Comment by arnaudlh** [comment]
> @arnaudlh I have the changes made, but cannot commit them. I am running on Window 10 + VS Code, WSL, Docker using Rover as remote container, but get the below error about python3.6 when I perform commit
> 
> ```
> > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
> /usr/bin/env: ‘python3.6’: No such file or directory
> ```

hi @jleonelion, its an error due to precommit calls, will be fixed in next rover, in the meantime, just remove precommit using the ```precommit uninstall``` command!

**Comment by jleonelion** [comment]
@LaurentLesle thank you for merging in my PR.  Should I assume this issue stays open until those merged changes are included in a release of the CAF module?
