### ISSUE TITLE
Kindly incorporate role_mapping for RBAC for Diagnostic storage accounts

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#295]
As discussed with @LaurentLesle opening this issue as Diagnostic Storage account was found to be missing in the list.

![image](https://user-images.githubusercontent.com/17183976/109159621-d3ce6d80-7742-11eb-8409-06a2b05caeae.png)

**Comment by LaurentLesle** [comment]
From now you can assign RBAC on the resource group as a work around

**Comment by LaurentLesle** [comment]
Closing as implemented.
