### ISSUE TITLE
Resource Lock

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#297]
Need capability to provide Locks (CanNotDelete, ReadOnly) at:

- [x] Subscription (committed in branch ben_mgmt_lock)
- [x] Resource Group  (committed in branch ben_mgmt_lock)
- [ ] Resource level (TBD)

As discussed with @LaurentLesle copying sample code below:

resource_groups = {

  // #
  // # Log Analytics resource groups
  // #

  la_eus_rg_01_ss = {
    name   = "rmazssprdhpblogrg001"
    region = "region1"
    tags   = {
    # "application_id"    =  "<sysid>"
      "application_id"    =  "hpb"
      "environment"       = "prd"
      "termination_date"  = "NONE"
      "created_by"        = "GlobalMonitoringEngineering@dtcc.com"
      "stack_name"        = "terraform"
      "data_class"        = "yellow"
    # "name"    =  "<sysid>-<environment>-<resource_type>"
      "name"              = "hpb-prd-loganalytics"
      "description"         = "resource group for monitoring"
    }
    **# Include this in aztfmod Issue 
    // resource_lock = {
    //   name = "lock for Log Analytics Resource Group"
    //   lock_level = "CanNotDelete"
    //   notes = "locked to prevent accidental deletion. Remove lock to delete"
    // }**
  }

**Comment by benhurjoel** [comment]
Archiving this issue due to low priority requirement.

**Comment by froblesmartin** [comment]
Hi! Could this be opened again? It would be nice to be able to configure locks with Terraform.

I have seen this PR https://github.com/aztfmod/terraform-azurerm-caf/pull/383 in which @manojtjacob was working on it, it got merged once, but not to `main` and instead to a branch which does not exist anymore (https://github.com/aztfmod/terraform-azurerm-caf/tree/ben_mgmt_lock) by @arnaudlh 

Sadly I haven't found any info about what happened with this development. Could you please let me know which is the status?
