### ISSUE TITLE
VMSS Module  

### ISSUE THREAD

**Issue by jorseng** [aztfmod/terraform-azurerm-caf#348]
- VMSS module for Linux OS
- VMSS module for Windows OS

**Comment by benhurjoel** [comment]
Thank you @jorseng for the initiative. On completion, need to associate VMSS to the Load Balancer Module as well : 

![image](https://user-images.githubusercontent.com/57881441/112424832-10a47900-8d70-11eb-89d8-1cf43287c441.png)

https://github.com/aztfmod/terraform-azurerm-caf/blob/master/load_balancers.tf
https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/networking/load_balancers/load_balancers.tf
