### ISSUE TITLE
Add support for managed boot diagnostics on VMs, etc.

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/terraform-azurerm-caf#368]
Need way to enable managed boot diagnostics on VMs created by aztfmod/caf.  Current implementation only enables boot diagnostics when `boot_diagnostics_storage_account_key` is defined, but it would be nice to have a way to enable boot diagnostics without having them go to an unmanaged storage account (perhaps a new bool attribute like `boot_diagnostics_managed`)?

"The recommended boot diagnostics experience is to use a managed storage account, as it yields significant performance improvements in the time to create an Azure VM." Source: [Azure boot diagnostics](https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics)

It looks like this capabilities is implemented in the azurerm provider: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8319
Although, it isn't well documented: https://github.com/terraform-providers/terraform-provider-azurerm/issues/9814

Assign to me, and I can give it a shot

**Comment by arnaudlh** [comment]
Good idea @jleonelion thanks for the suggestion. I will assign to you!

**Comment by medavamshi** [comment]
This is needed for azurerm_virtual_machine resource type as well.  not just linux or windows resource type

   63: boot_diagnostics {
│
│ The argument "storage_uri" is required, but no definition was found.

**Comment by thewriteway** [comment]
The azurerm_virtual_machine code should work when setting managed disk for diagnostic boot:

```
boot_diagnostics {
    enabled     = "true"
    storage_uri = ""
  }
```

**Comment by milan-todorovic** [comment]
By using terraform version v0.12.19 and azurerm provider v1.39.0 and in case I use
```
boot_diagnostics {
    enabled     = "true"
    storage_uri = ""
  }
```
to enable managed boot diagnostics, I get following error message when doing terraform apply:
```
Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Required parameter 'bootDiagnostics.storageAccountUri' is missing (null)." Target="bootDiagnostics.storageAccountUri"

  59: resource "azurerm_virtual_machine" "main" {
```
However terraform plan step do not complaint about this!
If I add storageAccountUri = "" instead of storage_uri = "" I get:
```
Error: Missing required argument

  on main.tf line 99, in resource "azurerm_virtual_machine" "main":
  99:   boot_diagnostics {

The argument "storage_uri" is required, but no definition was found.


Error: Unsupported argument

  on main.tf line 102, in resource "azurerm_virtual_machine" "main":
 102:     storageAccountUri =""

An argument named "storageAccountUri" is not expected here.
```
Any idea why this happens? I use azurerm_virtual_machine as resource. I need to configure managed boot diagnostics, not the unmanaged. Thank you in advance for any idea

**Comment by thewriteway** [comment]
@milan-todorovic 
I rerun it again today to test, I would suggest upgrading  your TF and provider versions as they are very outdated
My build runs on:
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.39.1

**Comment by milan-todorovic** [comment]
It definitely did on newer versions of provider and terraform. @thewriteway thank you

**Comment by milan-todorovic** [comment]
I can confirm after further testing that:
```
boot_diagnostics {
    enabled     = "true"
    storage_uri = ""
  }
```
works on terraform version 0.13 and azurerm version 2.27.0. Anything below this do not support managed boot diagnostic. Changelogs do not show anything specific for azurerm on version 2.27.0.
