### ISSUE TITLE
Feature request: vnet peering in different subscriptions

### ISSUE THREAD

**Issue by tenderitaf** [aztfmod/terraform-azurerm-caf#409]
Hi,
the current networking.tf peers only vnets on the same sub.
Would be great to support peering in different subs 

Thank you

**Comment by v4ld3r5** [comment]
Hi @tenderitaf,
Try setting both the `tfstate_subscription_id` and the `-target-subscription` when invoking the rover. The former is probably not needed, but we do for clarification. We have hub and spoke in different subscriptions and by setting that up it works fine.

Br

**Comment by tenderitaf** [comment]
@v4ld3r5 thanks for your answer, I'm not using rover. but even if I do peering requires terraform to  be 'aware' of both subs, according to the code there no provider change.

**Comment by v4ld3r5** [comment]
The rover does all the dirty work for you regarding the subscription as long as you provide those parameters when running it.
For the peering itself you don't really need the subscription, only the remote vnet id. 
With rover we run these tasks:
1. deploy hub with `-target_subscription 0001-xx-xx`
2. deploy spoke with `-target_subscription 0002-xx-xx`
3. setup peering hub->spoke with `-target_subscription 0001-xx-xx`
4. setup peering spoke->hub with `-target_subscription 0002-xx-xx`

Hope it helps

**Comment by tenderitaf** [comment]
Thanks @v4ld3r5, following you suggestion will imply at least 3 rover invocation, I'm not sure that this is intention.

@arnaudlh could you please clarify this, also I don't want to use rover for my deployment

**Comment by LaurentLesle** [comment]
@v4ld3r5  @tenderitaf  you are right for the 4 steps and you can do it with 3 invocations (steps 2 and 4 can be combined)

**Comment by LaurentLesle** [comment]
Closing as solution explained in the comment
