### ISSUE TITLE
Add sample for subscription creation

### ISSUE THREAD

**Issue by chris-p-martin** [aztfmod/terraform-azurerm-caf#411]
Is it possible to add samples for the new subscription creation submodule?

Thanks,
Chris

**Comment by dare-darryl** [comment]
Also curious how `refresh_access_token.sh` will affect the entire deployment flow.

**Comment by arnaudlh** [comment]
Closing as merged in https://github.com/aztfmod/terraform-azurerm-caf/pull/905
