### ISSUE TITLE
Use already existing managed_identity for virtual machines provisionning 

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#422]
In case AAD provisionning process is separate, would like to provide the ```managed_identity_ids``` from pre-existing resource instead of the object model  ```managed_identity_keys```

Configuration to look like: 

```hcl
   virtual_machine_settings = {
      linux = {
...
      identity = {
                type = "UserAssigned"
                managed_identity_ids = [
                  "resource_ID",
                  "resource_ID"
                ]
              }
```

**Comment by LaurentLesle** [comment]
Closing as implemented - https://github.com/aztfmod/terraform-azurerm-caf/blob/6d8514ef29ed4e4ffe698a85071d61f01644d02d/modules/compute/virtual_machine/managed_identities.tf#L20
