### ISSUE TITLE
Add support to create VM from image gallery

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#463]
REF: aztfmod/terraform-azurerm-caf#4

As part of level 3 solution deployment, we have the ability to create a shared image gallery. I am unable to find any documentation or reference on how to deploy a virtual machine from a shared image gallery. We need to support deploying a virtual machine from a shared image gallery published with the following configurations: 

- [ ] Shared Image gallery in the same subscription as the virtual machine
- [ ] Shared Image gallery in a different subscription but same tenant as the virtual machine
- [ ] Shared Image gallery in a different tenant and subscription

**Comment by arnaudlh** [comment]
hi @hriaz have you looked there? 

https://github.com/aztfmod/terraform-azurerm-caf/blob/32593cd85c33c988be595edd48a87fffcd5ea6e6/modules/compute/virtual_machine/vm_linux.tf#L101

So I look at this code, when you specify ```custom_image_id``` you should be able to create it.

As I'm looking at the shared image gallery module, we dont have the right output there: ```custom_image_ids```, so it will require a bit of updating.

**Comment by arnaudlh** [comment]
OK will have a deeper look @hriaz

**Comment by hriaz** [comment]
@arnaudlh Thanks for looking into this. I can confirm this worked for windows and Linux. This works in the latest modules after some tweaking.
