### ISSUE TITLE
Support for Random Strings 

### ISSUE THREAD

**Issue by jamesptruitt** [aztfmod/terraform-azurerm-caf#476]
Add support for Terraform Random String resource so that the user can user the random strings for passwords and others purposes

**Comment by LaurentLesle** [comment]
Can you provide some examples?

**Comment by jamesptruitt** [comment]
Example: I needed to generate a random string for my JWT key and store it in KeyVault during my CAF deployment.  I added the randon_string terraform module to my CAF modules repo to add this feature.
