### ISSUE TITLE
Add a secure way to pass container secure_environment_variables

### ISSUE THREAD

**Issue by RomanBurdiuzha** [aztfmod/terraform-azurerm-caf#478]
Module for creating container groups has option to pass secure_environment_variables to container instance.
Such kind of variables are useful to store secrets that are used by containers, for instance PAT for Azure DevOps.

Meanwhile there is no option to pass this data in a secure way, because module uses next variable assignment

https://github.com/aztfmod/terraform-azurerm-caf/blob/32593cd85c33c988be595edd48a87fffcd5ea6e6/modules/compute/container_group/container_group.tf#L31

Possible solutions:
1. read secure variables from environment variables (could be useful in CI/CD )
2. read secure variables from Key Vaults

**Comment by LaurentLesle** [comment]
@RomanBurdiuzha do you want to pick it up? your possible solution for 1 is similar to the environment variables who is merging the variables.
From Keyvault is also possible. Maybe to be split into another issue?

**Comment by RomanBurdiuzha** [comment]
> @RomanBurdiuzha do you want to pick it up? your possible solution for 1 is similar to the environment variables who is merging the variables.
Ok, let me try to do this

**Comment by RomanBurdiuzha** [comment]
@LaurentLesle it would be great if you help me to understand the correct way of operating with OS environment variables with in caf-terraform. I can't find any existing logic in current code where you are picking up variables from OS environment variables and merging them into configuration. So, I suppose code logic could be like this:
1. Introduce new variable in compute/container_group module. Variable could be like SECRETS_CONTAINER_INSTANCE
2. Variable will be loaded from OS environment variables if set
3. Merge it in locals.tf

Meanwhile I see some disadvantages of this way and want to ask if there any other workflow we could use.

**Comment by LaurentLesle** [comment]
implemented into - aztfmod/examples/compute/container_groups/100-aci-rover-github-runner
