### ISSUE TITLE
Add storage account protection techniques

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#484]
- [x] Enable soft delete for blobs
- [x] Enable soft delete for containers
- [ ] Enable point-in-time restore for containers
- [ ] Enable operational backup with Azure Backup

**Comment by arnaudlh** [comment]
The capabilities have been added also to LZ: https://github.com/Azure/caf-terraform-landingzones/commit/ff4acb9e8d3f047e3ca58ddb28ecec95761c9b30

**Comment by LaurentLesle** [comment]
Closing as implemented
