### ISSUE TITLE
Output named ssh_private_key_open_ssh whereas it is a public key

### ISSUE THREAD

**Issue by bnchou** [aztfmod/terraform-azurerm-caf#487]
https://github.com/aztfmod/terraform-azurerm-caf/blob/548dffef619faeb2b53be0b299dc6e376916efd7/modules/compute/virtual_machine/output.tf#L40

I would say that the name of the output should be ssh_public_key_open_ssh rather than ssh_private_key_open_ssh

**Comment by arnaudlh** [comment]
Agree on that one, it needs to be updated!
