### ISSUE TITLE
Add support for virtual wan s2s module

### ISSUE THREAD

**Issue by geraldfehringer** [aztfmod/terraform-azurerm-caf#491]
add https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_site to create virtual WAN based S2S IPSec connections, as well to add custome IKEv2 policies.

**Comment by arnaudlh** [comment]
hi @geraldfehringer this is currently under dev and should be here in June release

**Comment by LaurentLesle** [comment]
Coming with 5.4.0
