### ISSUE TITLE
Grant consent script failing

### ISSUE THREAD

**Issue by JvHd-vw** [aztfmod/terraform-azurerm-caf#499]
After the last update on the below script it raises a `ERROR: Bad Request({"error":{"code":"BadRequest","message":"Resource not found for the segment 'servicePrincipalsxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'... `. I presume due to a missing slash between servicePrincipals and ${resourceId}.

https://github.com/aztfmod/terraform-azurerm-caf/blob/7a8ddd4fabbc4ef8e1a78cba936b935ca44f65b3/modules/azuread/applications/scripts/grant_consent.sh#L19

**Comment by LaurentLesle** [comment]
good catch. Do you want to submit a patch?

**Comment by abdulrabbani00** [comment]
I have created a PR to resolve this issue, my apologies if I have not gone through the proper channels for submitting the PR, but I thought it was simple enough: https://github.com/aztfmod/terraform-azurerm-caf/pull/500

@LaurentLesle
