### ISSUE TITLE
Add support toggling "Allow Azure Services" to a SQL DB Server

### ISSUE THREAD

**Issue by jamesptruitt** [aztfmod/terraform-azurerm-caf#505]
Add support toggling "Allow Azure Services" to a SQL DB Server

Add azurerm_sql_firewall_rule to SQL Server

![Screen Shot 2021-06-08 at 9 01 29 AM](https://user-images.githubusercontent.com/54150331/121189713-584b8480-c838-11eb-8230-1c87cd34e53f.png)

**Comment by jamesptruitt** [comment]
I have added a PR to solve for this issue: [507](https://github.com/aztfmod/terraform-azurerm-caf/pull/507)

**Comment by arnaudlh** [comment]
hi @jamesptruitt, I think we already have that in the module as a capability with the 

https://github.com/aztfmod/terraform-azurerm-caf/blob/7a8ddd4fabbc4ef8e1a78cba936b935ca44f65b3/modules/databases/mssql_server/server.tf#L33 ?

this shows up in this example: https://github.com/aztfmod/terraform-azurerm-caf/blob/master/examples/mssql_server/109-sqlserver-network-firewall-rule/configurations.tfvars,

as per documentation provider, if you put 0.0.0.0 to both start and end IP address, you are achieving that purpose. 
    firewall_rules = {
      firewall_rule1 = {
        name             = "firewallrule1"
        start_ip_address = "0.0.0.0"
        end_ip_address   = "0.0.0.0"
      }
    }

as per: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_firewall_rule 

let me know if we still the PR!
thanks

**Comment by jamesptruitt** [comment]
No longer needed.  The functionality has been implemented
