### ISSUE TITLE
MS SQL database creation failure because of var.cloud.sqlServerHostname 

### ISSUE THREAD

**Issue by m-m-g-s** [aztfmod/terraform-azurerm-caf#506]
Configuration:
```
mssql_databases = {
  tds_sql_db = {
    name               = "tds"
    resource_group_key = "tds_rg"
    mssql_server_key   = "tds_sql"
    max_size_gb        = 10
    sku_name           = "GP_S_Gen5_2"
    min_capacity       = 1
    auto_pause_delay_in_minutes = 60
  }
}
```
Running terraform plan
```
Upgrading modules...
Downloading aztfmod/caf/azurerm 5.3.10 for solution...
- solution in /home/vscode/.terraform.cache/modules/solution
...
- solution.mssql_databases in /home/vscode/.terraform.cache/modules/solution/modules/databases/mssql_database
...
╷
│ Error: Invalid template interpolation value
│ 
│   on /home/vscode/.terraform.cache/modules/solution/modules/databases/mssql_database/main.tf line 11, in locals:
│   11:   server_name = "${var.server_name}${var.cloud.sqlServerHostname}"
│     ├────────────────
│     │ var.cloud.sqlServerHostname is object with no attributes
│ 
│ Cannot include the given value in a string template: string required.
╵
Error on or near line 255: Error running terraform plan; exiting with status 
```

It worked well with at least aztfmod/caf/azurerm 5.3.7

**Comment by arnaudlh** [comment]
hi @davesee can you please have a look on this one?

**Comment by davesee** [comment]
@m-m-g-s please let me know if you updated your caf_solution landingzone.

The variables are defaulted in the latest version here:
https://github.com/Azure/caf-terraform-landingzones/blob/master/caf_solution/variables.cloud.tf

Also there is a new rover release that sets the cloud vars to the current cloud values:
https://github.com/aztfmod/rover/blob/43eb7ddc62f81a5dd6e7fddd0e315beb8fa10ced/scripts/functions.sh#L545

You can also try setting it in the shell via
sqlServerHostname=$(az cloud show | jq -r ".endpoints.microsoftGraphResourceId")
export TF_VAR_sqlServerHostname=$sqlServerHostname

**Comment by m-m-g-s** [comment]
@davesee thank you for the tip. it helped.
