### ISSUE TITLE
Add Support for Azure VMWare Service

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#510]
We are currently missing support for Azure VMWare service in CAF. We need to add support for https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vmware_cluster

**Comment by hriaz** [comment]
After discussing with @arnaudlh and @LaurentLesle including Microsoft GBB for AVS, it doesn't make sense to include this module.

**Comment by arnaudlh** [comment]
Reopening as @SergioMiyama is working on this one.

**Comment by LaurentLesle** [comment]
Closing as added in 5.4.3
