### ISSUE TITLE
Add Support for Azure File Storage Queues in Storage Accounts

### ISSUE THREAD

**Issue by jamesptruitt** [aztfmod/terraform-azurerm-caf#516]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_queue

**Comment by arnaudlh** [comment]
Hi @jamesptruitt do you have bandwidth to work on it and want to be assigned? thanks

**Comment by gavination** [comment]
Hi @arnaudlh. I took this one on and published a [PR found here](https://github.com/aztfmod/terraform-azurerm-caf/pull/538/files)
