### ISSUE TITLE
Unable to assign NSG flow logs to custom defined network watcher

### ISSUE THREAD

**Issue by swilkodev** [aztfmod/terraform-azurerm-caf#527]
In the scenario where I define a network watcher as per below
```hcl
network_watchers = {
    nwaue = {
        name = "aue"
        resource_group_key = "network"
        region             = "primary"
    }
}
```

When I attempt to link the NSG flow logs to a network watcher resource using  (network_watcher_key, network_watcher_rg_key), I find it does not work. 

```hcl
flow_logs = {
      version = 2
      enabled = true
      # we pick the default network watcher inside #NetworkWatcherRG
      # we use the network watcher in the current region (created by default)
      # this can be overwritten by specifying the following fields:
      network_watcher_key = "nwaue"
      network_watcher_rg_key = "network"
```
The NSG flows module always tries to link to a network watcher which uses the default resource group name (NetworkWatcherRG) and naming convention (in my case "NetworkWatcher_australiaeast"). Therefore I get this error on terraform apply

(Network Watcher "NetworkWatcher_australiaeast" / Resource Group "NetworkWatcherRG"): network.WatchersClient#SetFlowLogConfiguration: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/networkWatchers/NetworkWatcher_australiaeast' under resource group 'NetworkWatcherRG' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

Looking at the code I believe the following is contributing to the issue.

- The network watcher flow log module uses the network_watcher_rg_key to lookup the network watcher resource group, however
I think the first lookup will always fail as it is using the network_watchers list rather than the resource groups list to retrieve
the RG name.

https://github.com/aztfmod/terraform-azurerm-caf/blob/b7572e34382340d7dc4f33be70b342865d0c7e78/modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf#L6

- network_watchers variable is not passed from the virtual network module to the nsg module therefore defaults to empty

https://github.com/aztfmod/terraform-azurerm-caf/blob/b7572e34382340d7dc4f33be70b342865d0c7e78/modules/networking/virtual_network/module.tf#L62

**Comment by arnaudlh** [comment]
Thanks @swilkodev for the detailed analysis. do you have a fix and want to try a PR or should we push further for triage and fix with the core team?

**Comment by swilkodev** [comment]
@arnaudlh sorry for the delay, tried to fix the issue, but no luck.. 

I found the network_watchers collection also seems to be keyed by the landing zone.  I also noticed the virtual network module contains two variables - network_watchers and netwatcher. I'm not familiar with the code base so best if the core team triages.

**Comment by arnaudlh** [comment]
@swilkodev - no problem we are working on it - @SergioMiyama

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
