### ISSUE TITLE
Add Support for AzureBastion

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#530]
Azure Bastion Service support appears to be missing. This is now commonly deployed in most enterprises. We do see a reference for Azure Bastion Host in [azurerm_bastion_host](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host)

**Comment by arnaudlh** [comment]
hi @hriaz, this is indeed implemented: 

- Code: https://github.com/aztfmod/terraform-azurerm-caf/blob/e42fcd22f6a333e5888e5d0512cb158537cb2596/bastion_service.tf

- Example: https://github.com/aztfmod/terraform-azurerm-caf/blob/8538f30525720248e6198506e817941e9094a99d/examples/networking/virtual_network/200-nsg-flow-logs/configuration.tfvars

**Comment by hriaz** [comment]
@arnaudlh Just tested and it works! Thank you. It was definitely a hidden gem.
