### ISSUE TITLE
IMPORTANT: Changing enable_automatic_updates from false to true causing Virtual machine to be replaced

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#531]
We are able to reproduce this issue. If enable_automatic_updates is toggled, terraform destroys the virtual machine. This is a major issue as a VM could be destroyed in production
 ~ enable_automatic_updates     = false -> true # forces replacement

**Comment by arnaudlh** [comment]
As per the provider and documented here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine

**Comment by LaurentLesle** [comment]
@hriaz this is the current behavior of the TF provider. Would be good to confirm the same applies with the az cli or powershell. If you can change with those tools without a reboot then yes it is a but to be reported on the azurerm.

**Comment by arnaudlh** [comment]
Feels like its a create time action as per: https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#enable-automatic-vm-guest-patching

**Comment by arnaudlh** [comment]
@hriaz - if you explicitly set it to ```enable_automatic_updates = false``` you are not able to modify it afterwards, even with az cli or powershell: 

```
az vm update --resource-group rmyd-rg-example-virtual-machine-rg2-yt --name vm-examplevm3  --set osProfile.windowsConfiguration.enableAutomaticUpdates=true osProfile.windowsConfiguration.patchSettings.patchMode=AutomaticByPlatform
```
gets:
```
(PropertyChangeNotAllowed) Changing property 'windowsConfiguration.enableAutomaticUpdates' is not allowed.
```

**Comment by arnaudlh** [comment]
Will close this one as by-design and not due to TF or CAFTF.
