### ISSUE TITLE
At least one FQDNs is required on app gateway backend pool

### ISSUE THREAD

**Issue by swilkodev** [aztfmod/terraform-azurerm-caf#535]
I encountered an issue where if I don't specify at least one FQDN for an application gateway application backend pool, I receive the following error.

**Error: backend_address_pool.0.fqdns: attribute supports 1 item as a minimum, config has 0 declared**

```hcl
application_gateway_applications = {
  aspnetapp_az1_agw1 = {

   ...

    backend_pool = {
            ip_addresses = [
                "10.1.0.5"
            ]
        }
   }
}
```
FQDNs are optional for the backend pool as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#fqdns

The configuration needs to allow either ip_addresses or FQDNs

The issue seems to be the following code

https://github.com/aztfmod/terraform-azurerm-caf/blob/b7572e34382340d7dc4f33be70b342865d0c7e78/modules/networking/application_gateway/locals.backend_pools.tf#L31-L36

fqdns = try(value.backend_pool.fqdns, null) obviously works but I couldn't figure out the fix. Thoughts?

**Comment by laingsc** [comment]
I encountered the same thing and I ended up using an IP address in fqdns and that worked.

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
