### ISSUE TITLE
logged_in_user for keyvault still gets applied when using MSI / Service Principal 

### ISSUE THREAD

**Issue by pmatthews05** [aztfmod/terraform-azurerm-caf#541]
Set up a keyvault to add logged_in_user

```
secrets = {
    name = "secrets"
    resource_group_key = "security"
    region = "region1"
    sku_name = "premium"
    soft_delete_enabled = true

    diagnostic_profiles = {
      operations = {
        definition_key   = "default_all"
        destination_type = "log_analytics"
        destination_key  = "central_logs"
      }
      siem = {
        definition_key   = "siem_all"
        destination_type = "storage"
        destination_key  = "all_regions"
      }
    }

    creation_policies = {
      logged_in_user = {
        # if the key is set to "logged_in_user" add the user running terraform in the keyvault policy
        # More examples in /examples/keyvault
        secret_permissions = ["Set", "Get", "List", "Delete", "Purge", "Recover"]
      }
    }
```

From my understanding the logged_in_user section runs the following code:
https://github.com/aztfmod/terraform-azurerm-caf/blob/aa08aa795259a7b79dfd0a5e151fc7eb7b55dfc5/modules/security/keyvault_access_policies/policies.tf#L28

When I'm logged in as a user, then I would expect the user to be added to the keyvault. However, the line 32
`if key == "logged_in_user" && var.client_config.logged_user_objectId != null `
seems to state that if I'm logged in as Service Principal, or MSI then var.client_config.logged_user_objectId should be null, as the var.client_config.logged_aad_app_objectId should be populated instead, and the current logged in user (MSI/Service Principal) shouldn't be added.

Currently it still attempts to add the MSI/Service Principal as the logged_in_user, which then fails with an error message, as following the starter templates scenario 200, the MSI's and 'caf_launchpad_level0' service principal have already been added to the keyvaults secrets policy, when first run as my user account.

Shouldn't need to comment out the creation_policies -> logged_in_user for keyvaults when running as MSI/Service Principal as this breaks the idempotency of the config files.

**Comment by LaurentLesle** [comment]
Hi @pmatthews05 logged_in_user should only be used when using interactive deployment from vscode. If you transition to SP and MSI you need to remove it and also include azuread_group in your keyvault access policies to grant users to keyvault if needed.

So your last statement is correct.

**Comment by pmatthews05** [comment]
My last statement says shouldn't need to comment out the logged_in_user, but you have to when switching from User to SP or MSI, because they have already been added access to the keyvault when ran as a user. Then the code attempts to add them as the current user and terraform complains that they are already in the environment but not part of the state file.

I understand it needs the logged in user when using it interactively from VSCode, otherwise that person would not have access. Then when run from the pipeline you need to comment out or remove the "logged_in_user". This is the only way I've been able to make it work as you stated.

However, I, and the people I currently work with, are under the impression that code shouldn't need to be changed between environments/mechanisms. I shouldn't need to run the code one way, then check in differently to run it again via pipelines. Then if someone was running it from their laptop, have to check out the code and re-instate all the commented out code to run it themselves. Doesn't help there is also a company policy that nothing can be deployed/install into a production environment using user accounts.

I suppose the argument for you is that these are 'configuration files', and not true code files.  

Our desired outcome, would be able to deploy to different azure environments using the same configuration files, pointing to the same azure DevOps repository that would have pipelines that can deploy to the different environments, the only difference would be the prefix for all the resources names. (Including Organisation and project agents). The prefix would be passed in as a variable into the Rover call.

Having to create multiple configuration files for different environments, then adding or updating something requires to ensure you have added it to all the other configuration files to keep the environments in sync. It's prone to human error and mistakes.

I've moved away from the original issue, but just wanted to explain, even though CAF work you are doing is awesome, how we work.

**Comment by LaurentLesle** [comment]
closing
