### ISSUE TITLE
[feature] To add random suffix to L4 MSI string

### ISSUE THREAD

**Issue by angde1990** [aztfmod/terraform-azurerm-caf#546]
A short random suffix can be added to the MSI string to make the string unpredictable and unguessable. This is to add another security layer to making it harder to guess another application's MSI string.

Example:
level4-azdo-myApplicationA-abcdeg
level4-azdo-myApplicationB-hijkln

**Comment by arnaudlh** [comment]
Merged and available in 5.4.0. thanks @angde1990 for the issue!
