### ISSUE TITLE
mssql server module should implement keyvault_key

### ISSUE THREAD

**Issue by rmul** [aztfmod/terraform-azurerm-caf#548]
Example https://github.com/aztfmod/terraform-azurerm-caf/blob/master/examples/mssql_server/102-sqlserver-extend/configuration.tfvars shows how to provide a keyvault_key to store the random generated sql admin password, but this has no effect. Looking at the code and comparing with for instance mysql server confirms the usage of keyvault_key is not implemented in the mssql_server submodule:

```
  administrator_login_password  = try(var.settings.administrator_login_password, random_password.sql_admin.0.result)
```

**Comment by iriahk89** [comment]
This has been addressed in this PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/563/files will assign the issue there as well

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
