### ISSUE TITLE
diagnostic_profiles are not passed to firewall submodule

### ISSUE THREAD

**Issue by rmul** [aztfmod/terraform-azurerm-caf#550]
In modules/networking/firewall/diagnostics.tf there is code to add diagnostic profiles to a firewall using the diagnostic_profiles variable, but in the networking_firewall.tf this variable is not passed to the module. Thus no diagnostics settings are applied to the firewall.

**Comment by arnaudlh** [comment]
thanks for reporting @rmul, this will be fixed in 5.4.0 due very soon.
