### ISSUE TITLE
Refactor references to resource groups

### ISSUE THREAD

**Issue by GlennChia** [aztfmod/terraform-azurerm-caf#556]
# Description

Current approach:

The current approach is an improvement on the previous version where the resource groups was only referencing those initialized by the local state that uses `local.resource_groups`. Instead, we added the option of referencing the remote state using the `local.combined_objects_resource_groups`. An example of this is how the `name` was extracted from `local.combined_objects_resource_groups`

```terraform
local.combined_objects_resource_groups[try(each.value.lz_key, local.client_config.landingzone_key)][each.value.resource_group_key].name
```

# Limitations of the above approach

The problem with the above approach was that it was highly dependent on `each.value.lz_key` which is a common key declared per resource initialized. There could be scenarios where there is a requirement to reference a resource group that is not located in the environment that was setup by this `lz_key`. Hence, this issue proposes a refactoring at the resource (in the `modules` directory) and the module (at the `root` directory). In addition, this approach also prevents users from specifying a resource_group_id or resource_group_name directly since it must always use the `local.combined_objects_resource_groups`. This can be improved as explained in the section below.

# Proposed new solution

## examples - configuration.tfvars

```terraform
# Option 1
resource_group = {
      lz_key = "examples"
      key = "test"
}
# Option 2
resource_group = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup1"
}
```

- Option one allows the user to reference a specific `lz_key` and `key` for a resource group. This makes it more fine grained
- Specifying the `id` itself is the most specific way to reference the resource group

## root

Reference each of the above using the `coalesce` function. An example to extract the `id` is shown below:

```terraform
resource_group_id = coalesce(
  try(each.value.resource_group.id, null),
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group.key].id, null),
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group_key].id, null),
)
```

To reference the full individual resource group object

```terraform
resource_group = coalesce(
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group.key], null),
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group_key], null),
)
```

- Note that the second line that uses `each.value.resource_group_key` is present for backward compatibility.

For multiple resource groups, exclude the `each.value.resource_group.key`

```terraform
resource_groups = local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)]
```

The best way would be to pass the entire `resource_groups` object and reference it the specific resource_group and its attributes at the resource level (within the modules directory)

# For discussion

Replace `try` with `coalesce`

With `try`

```terraform
resource_group = coalesce(
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group.key], null),
  try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group_key], null),
)
```

With only `coalesce`

```terraform
resource_group = coalesce(
  try(local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group.key], null),
  try(local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group.key], null),
  try(local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group_key], null),
  try(local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group_key], null),
)
```

- Makes the lines shorter and could work better with `plan` and `apply`

**Comment by LaurentLesle** [comment]
Have you tried this variation? Same behavior?:

```hcl
resource_group = try(
  local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group.key],
  local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group.key],
  local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group_key],
  local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group_key],
  null
)
```

**Comment by GlennChia** [comment]
Yes, the behavior is indeed the same and I think this is the cleanest pattern with the least `try` blocks.

Validated this using the `msi` example with `rover -lz /tf/caf/examples -var-folder /tf/caf/examples/managed_service_identity/100-msi-levels/ -level level1 -a apply` and checked the tags in the Azure portal

`examples/managed_service_identity/100-msi-levels/configuration.tfvars`: Use both the modern reference and the soon to be deprecated `resource_group_key` and both works

```hcl

global_settings = {
  default_region = "region1"
  regions = {
    region1 = "southeastasia"
  }
}

resource_groups = {
  msi_region1 = {
    name   = "security-rg1"
    region = "region1"
  }
}

managed_identities = {
  level0 = {
    # Used by the release agent to access the level0 keyvault and storage account with the tfstates in read / write
    # Assign read access to level0
    name = "msi-level0"
    resource_group = {
      # lz_key = "examples"
      key = "msi_region1"
    }
    # resource_group_key will be deprecated in the future
    # resource_group_key = "msi_region1"
    tags = {
      level = "level0"
    }
  }
  level1 = {
    # Used by the release agent to access the level1 keyvault and storage account with the tfstates in read / write
    # Assign read access to level0
    name = "msi-level1"
    resource_group = {
      # lz_key = "examples"
      # key = "msi_region1"
    }
    # resource_group_key will be deprecated in the future
    resource_group_key = "msi_region1"
    tags = {
      level = "level1"
    }
  }
```

`modules/security/managed_identity/managed_identity.tf`: Destructure the `resource_groups`

```hcl
resource "azurerm_user_assigned_identity" "msi" {
  name = azurecaf_name.msi.result
  resource_group_name = try(
    var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group.key].name,
    var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group.key].name,
    var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group_key].name,
    var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group_key].name,
    null,
  )
  location = try(
    var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group.key].location,
    var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group.key].location,
    var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group_key].location,
    var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group_key].location,
    null,
  )
  tags = try(
    merge(
      try(var.global_settings.inherit_tags, false) ?
      try(
        var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group.key].tags,
        var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group.key].tags,
        var.resource_groups[var.settings.resource_group.lz_key][var.settings.resource_group_key].tags,
        var.resource_groups[var.client_config.landingzone_key][var.settings.resource_group_key].tags,
        null,
      ) : {},
      local.tags
    ),
    {}
  )
}
```

`managed_identities.tf` : At the root level pass in the combined resource groups

```hcl
module "managed_identities" {
  source   = "./modules/security/managed_identity"
  for_each = var.managed_identities

  client_config   = local.client_config
  global_settings = local.global_settings
  name            = each.value.name
  resource_groups = local.combined_objects_resource_groups
  settings        = each.value
}
```

> Have you tried this variation? Same behavior?:
> 
> ```terraform
> resource_group = try(
>   local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group.key],
>   local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group.key],
>   local.combined_objects_resource_groups[each.value.resource_group.lz_key][each.value.resource_group_key],
>   local.combined_objects_resource_groups[local.client_config.landingzone_key][each.value.resource_group_key],
>   null
> )
> ```

**Comment by GlennChia** [comment]
Seems like the new pattern has some issues with the Terraform plan as stated by Arnaud in #610. Perhaps we should revert back the the `coalesce` approach? @LaurentLesle

**Comment by KurdoTree** [comment]
@GlennChia @LaurentLesle ,

I tried your approach(s) for obtaining the id (as well as the ones in many other established modules).
But no madder which approach I try, I allways get this (which driven my nuts since days):

`
**each.value.someObject** is object with 2 attributes    (is correct)
**each value.someObject.key** is "myobj_1"                  (is correct, I want its id!!)
**local.client_config.landingzone_key** is "example"
**local.combined_objects_my_new_module** is object with 1 attribute "examples"`

... object does't have attribute "id"

Any hint, on what I'm doing wrong, would nice.
