### ISSUE TITLE
Add support for Remote Key Reference for dns_servers in virtual_network

### ISSUE THREAD

**Issue by seanlok** [aztfmod/terraform-azurerm-caf#567]
As `dns_servers` [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network#dns_servers) can set the ip as ` dns_servers = ["ip1", "ip2"] `. It will also be great to have support to refer to the remote key state like:

```
dns_servers = { 
  lz_key = lz_key_name
  key      = key_name
  ...
}
```

Reference to the existing file in aztfmod are:
`aztfmod/modules/networking/virtual_network/module.tf`

which existing settings is:
`dns_servers = lookup(var.settings.vnet, "dns_servers", null)`

**Comment by LaurentLesle** [comment]
@seanlok You want to reference the private remote ip address of Azure Firewall or from a virtual machine?

**Comment by seanlok** [comment]
yeah. That will be great. else just have to hardcode the respective dns server in different segment.

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
