### ISSUE TITLE
Azure Cognitive Services

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#568]
We need to add support for Azure Cognitive services referenced [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account)

**Comment by abdulrabbani00** [comment]
I will be working on this task: @arnaudlh.

**Comment by abdulrabbani00** [comment]
Hello @arnaudlh, I have created the [following PR](https://github.com/aztfmod/terraform-azurerm-caf/pull/596).

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
