### ISSUE TITLE
[feature] Application Gateway Custom Probe

### ISSUE THREAD

**Issue by rickychew77** [aztfmod/terraform-azurerm-caf#579]
Feature request to support custom probe in application gateway.

**Comment by arnaudlh** [comment]
hi @rickychew77 , does that #574 work for you?

**Comment by rickychew77** [comment]
@arnaudlh  that looks good. let's track this issue with that PR. thanks Arnaud!

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
