### ISSUE TITLE
Missing output in "event_hub_namespaces" module

### ISSUE THREAD

**Issue by edgarhe4** [aztfmod/terraform-azurerm-caf#583]
Hello,

I am trying to configure a [private endpoint](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/examples/networking/private_links/endpoints/centralized/eventhub_namespaces.tfvars) for Event Hub resource but I am raising an error "try(var.remote_objects.event_hub_namespaces[each.value.lz_key][each.key].id, var.remote_objects.event_hub_namespaces[var.client_config.landingzone_key][each.key].id)"

We can identify that the "output" is missing here https://github.com/aztfmod/terraform-azurerm-caf/blob/master/event_hubs.tf

output "event_hub_namespaces" {
  value = module.event_hub_namespaces
}

FYI we did the change in our local environment and including the output is fixed but it should be fixed here in this repo

Regards
Edgar Hernandez

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
