### ISSUE TITLE
App gateway path based routing rules issue

### ISSUE THREAD

**Issue by swilkodev** [aztfmod/terraform-azurerm-caf#586]
Using the below configuration to express path based routing rules for an application gateway.

```hcl
    listeners = {
        public_https = {
            name                               = "public-443"
            front_end_ip_configuration_key     = "public"
            front_end_port_key                 = "443"
            host_name                          = "somehostname"
            request_routing_rule_key           = "path_based"
        }
    }

    request_routing_rules = {
      path_based = {
        rule_type = "PathBasedRouting"
        url_path_map_key = "public-443-map"
      }
    }

    url_path_maps = {
        public-443-map = {
            name = "public-443-map"
            path_rules = {
                pathRuleIdentity = {
                    name    = "pathRuleIdentity"
                    paths   = ["/identity*"]
                }

                pathRuleAuthorisation = {
                    name    = "pathRuleAuthorization"
                    paths   = ["/authorization*"]
                }
            }
        }
    }
```
I encounter the following error.

   on .terraform\modules\caf-deploy\modules\networking\application_gateway\application_gateway.tf line 134, in resource "azurerm_application_gateway" "agw":     
  134:           backend_address_pool_name     = try(var.application_gateway_applications[path_rule.value.backend_pool.app_key].name, var.application_gateway_applications[path_rule.value.backend_pool.app_key].name)
     ├────────────────
     │ path_rule.value is object with 2 attributes
     │ var.application_gateway_applications is object with 1 attribute "aspnetapp_az1_agw1"

 Call to function "try" failed: no expression succeeded:
 - Unsupported attribute (at .terraform\modules\caf-deploy\modules\networking\application_gateway\application_gateway.tf:134,99-112)
   This object does not have an attribute named "backend_pool".
 - Unsupported attribute (at .terraform\modules\caf-deploy\modules\networking\application_gateway\application_gateway.tf:134,180-193)
   This object does not have an attribute named "backend_pool".

 At least one expression must produce a successful result.

To fix the issue, line 134 can be changed from

```
backend_address_pool_name     = try(var.application_gateway_applications[path_rule.value.backend_pool.app_key].name, var.application_gateway_applications[url_path_map.value.backend_pool.app_key].name)
```
to 

```
backend_address_pool_name     = try(var.application_gateway_applications[path_rule.value.backend_pool.app_key].name, var.application_gateway_applications[url_path_map.value.app_key].name)
```

I think the first expression in the try will also never resolve. Perhaps line 134 should just be

```
backend_address_pool_name     = try(var.application_gateway_applications[url_path_map.value.app_key].name)
```

Let me know your thoughts and I'll submit a PR.

**Comment by iriahk89** [comment]
your configuration should be updated as below:

…
url_path_maps = {
        public-443-map = {
            name = "public-443-map"
            path_rules = {
                pathRuleIdentity = {
                    name    = "pathRuleIdentity"
                    paths   = ["/identity*"]
                    backend_pool = {
                      app_key = "backend_pool_key"
                    }
                    backend_http_setting = { # Leave empty it's taking default http_setting of this application
                    }
                }

                pathRuleAuthorisation = {
                    name    = "pathRuleAuthorization"
                    paths   = ["/authorization*"]
                    backend_pool = {
                      app_key = "backend_pool_key"
                    }
                    backend_http_setting = { # Leave empty it's taking default http_setting of this application
                    }
                }
            }
        }
    }
…

**Comment by iriahk89** [comment]
backendpool need to be added as traffic can be redirect to different backend pool

**Comment by swilkodev** [comment]
Understand the requirement. However the intent I believe is it should default to the apps backend settings, when not specified. Specifying a blank setting is cumbersome. The first expression in the try should resolve to a specific backend if specified, otherwise it should fall back to the app.

The following two statements, for the backend settings are not consistent, hence what my PR was addressing.

backend_address_pool_name  = try(var.application_gateway_applications[path_rule.value.backend_pool.app_key].name, var.application_gateway_applications[path_rule.value.backend_pool.app_key].name)
          

backend_http_settings_name = try(var.application_gateway_applications[path_rule.value.backend_http_setting.app_key].name, var.application_gateway_applications[url_path_map.value.app_key].name)

**Comment by iriahk89** [comment]
ok my bad..let me reopen the PR and approve...LGTM

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
