### ISSUE TITLE
Azure Kubernetes examples are incomplete and do not work

### ISSUE THREAD

**Issue by swetha-sundar** [aztfmod/terraform-azurerm-caf#595]
## Issue:

Two out of the four AKS examples (103-multi-clusters and 104-private-cluster) are incomplete and do not successfully run/execute. 

### 103-multi-clusters

**terraform plan output: ** 

<img width="1048" alt="Screenshot 2021-07-20 at 5 30 32 PM" src="https://user-images.githubusercontent.com/42051002/126298208-bdc6f4da-6944-490a-951f-dd4ba9432214.png">

### 104-private-cluster

**terraform plan output: ** 

<img width="1048" alt="Screenshot 2021-07-20 at 5 25 50 PM" src="https://user-images.githubusercontent.com/42051002/126297368-882095e8-6eba-4b65-a355-8f4176107170.png">

**Comment by swetha-sundar** [comment]
Created a PR to fix the issues here: https://github.com/aztfmod/terraform-azurerm-caf/pull/594

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
