### ISSUE TITLE
[bug] Call to function "coalesce" failed when defining routes

### ISSUE THREAD

**Issue by angde1990** [aztfmod/terraform-azurerm-caf#598]
rover version: aztfmod/rover:1.0.1-2106.3012
lz branch: 2107.1

![image](https://user-images.githubusercontent.com/17272364/126432080-f3fe8bd9-62a8-477a-ba44-56fb31805e55.png)

**Comment by arnaudlh** [comment]
dupes with #575

**Comment by LaurentLesle** [comment]
Close as fixed in 5.4.2

**Comment by tanvp112** [comment]
@LaurentLesle @jorseng 
The fix would assign ip_address_fw to null, but this null value would trigger failure when adding route to the route table. I am using the "standalone" method, can anyone advise how to correctly assign a standard Firewall private IP to a route?

```
Error: Error in function call

   on .terraform\modules\instinct\modules\networking\routes\module.tf line 7, in resource "azurerm_route" "route":
    7:   next_hop_in_ip_address = try(lower(var.next_hop_type), null) == "virtualappliance" ? coalesce(var.next_hop_in_ip_address, var.next_hop_in_ip_address_fw, var.next_hop_in_ip_address_vm) : null

     var.next_hop_in_ip_address is null
     var.next_hop_in_ip_address_fw is null
     var.next_hop_in_ip_address_vm is null

Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
