### ISSUE TITLE
Module gone from Terraform Registry

### ISSUE THREAD

**Issue by picardsrcd** [aztfmod/terraform-azurerm-caf#60]
Overnight, the module disappeared from terraform registry

This URL now returns 404:
https://registry.terraform.io/modules/aztfmod/caf-enterprise-scale/azurerm/

```
module "launchpad" {
  source  = "aztfmod/caf-enterprise-scale/azurerm"
  version = "~>0.3"
```

**Comment by picardsrcd** [comment]
Workaround till this is resolved:
```
module "launchpad" {
  # source  = "aztfmod/caf-enterprise-scale/azurerm"
  # version = "~>0.3"
  source = "git@github.com:aztfmod/terraform-azurerm-caf.git?ref=0.3.8"
  # version = "~>0.3"
```

**Comment by arnaudlh** [comment]
hi @picardsrcd  its not gone, just been renamed to be simpler, you can find it:  https://registry.terraform.io/modules/aztfmod/caf/azurerm
and call it: 
module "launchpad" {
  source  = "aztfmod/caf/azurerm"
  version = "~>0.3"
}

**Comment by picardsrcd** [comment]
Thanks. Oddly enough, the registry still showed the module, but when you clicked it, it went 404.

Is there a website that provides an overview of changes for the Enterprise CAF from a roadmap and updates perspective? There's been a lot of changes in repos, some archived, renamed, vnext changes. I find myself trying to connect the dots all over the place

**Comment by arnaudlh** [comment]
hi @picardsrcd agree with you on the changes, I'm going to publish a blogpost and videos soon - and expect some commits that will clarify many things :)

**Comment by picardsrcd** [comment]
closing issue. Thanks for the update. Please follow up on the registry to make sure stale modules ....dissapear
