### ISSUE TITLE
Storage - Share file needs to be added to CAF

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#614]
Currently, we have the ability to create a share and directory in a storage account. We need to add the ability to upload local files in the share. This is a required function if you are bootstrapping NVA's. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share_file

@abdulrabbani00 FYI

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
