### ISSUE TITLE
Firewall subnet id should be optional

### ISSUE THREAD

**Issue by seanlok** [aztfmod/terraform-azurerm-caf#617]
in `networking_firewall.tf` the subnet_id is 
`subnet_id           = module.networking[each.value.vnet_key].subnets["AzureFirewallSubnet"].id`

probably can use:
`subnet_id           = try(module.networking[each.value.vnet_key].subnets["AzureFirewallSubnet"].id,null)`

Accoding to the documentation, the subnet id should be optional. Especially when a secure hub firewall is used. No vnet is required. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#subnet_id

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
