### ISSUE TITLE
Restored VM OS Disk is getting recreated with existing VM configuration

### ISSUE THREAD

**Issue by jorseng** [aztfmod/terraform-azurerm-caf#624]
Scenario:
When a VM that is deployed and managed by CAF module is restored from Azure Backup in portal, the existing VM os_disk name diverged from the restored os_disk causing Terraform to recreate the VM in the next apply.

Steps to recreate:
1. Deploy VM using CAF module
2. Enable backup for the deployed VM
3. In Azure Portal, restore VM by swapping os_disk with the restored os_disk.
4. Run plan/apply on the same VM configuration to see the change to recreate the VM.

Discovery:
For restored os_disk, the only attribute that diverged from the existing state was the disk name itself and any changes to os_disk name will cause a recreation of VM. 
The os_disk name restored from Azure Backup is appended with the restoration date and time which is automated by Azure Backup.

**Comment by arnaudlh** [comment]
Closing as integrated into 5.4.2
