### ISSUE TITLE
App Gateway - Support for rewrite_rule_set

### ISSUE THREAD

**Issue by laingsc** [aztfmod/terraform-azurerm-caf#630]
We've a need to set reply headers for CORS support.  rewrite_rule_set will enable this for us!

Cheers

**Comment by swilkodev** [comment]
PR #592 support rewrite rules. Its was merged into the integration branch so should be available soon.

**Comment by arnaudlh** [comment]
hi @laingsc as @swilkodev mentionned and contributed, it is now in 5.4.2 release, so I will close this one for now. dont hesitate to open an issue if you are facing problems using it.
thanks
Arnaud
