### ISSUE TITLE
Application Gateway improvement: Isolation for platform and application specific sub resources

### ISSUE THREAD

**Issue by iriahk89** [aztfmod/terraform-azurerm-caf#633]
Maintenance is high for current application gateway implementation which everything track in single resources.
Decouple application specific sub resources of agw to improve scalability and maintenance

**Comment by LaurentLesle** [comment]
Closing as now in 5.4.3

**Comment by nusrath432** [comment]
@iriahk89 Hi, Could you add some README.md or notes to the examples section please. 

I need to add an app-gw before my AKS cluster - which of the following do I use and what's the purpose of other two?
- application_gateway
- application_gateway_applications_v1
- application_gateway_platforms

Thanks
