### ISSUE TITLE
Application Gateway - Probes block shouldn't have mandatory 'host'

### ISSUE THREAD

**Issue by laingsc** [aztfmod/terraform-azurerm-caf#639]
See: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#probe

Perhaps some null defaults and tries and a few more defaults like:

    content {
      name                                      = probe.value.name
      protocol                                  = try(probe.value.protocol, "Https")
      host                                      = try(probe.value.host, null)
      pick_host_name_from_backend_http_settings = try(probe.value.pick_host_name_from_backend_http_settings, false)
      port                                      = try(probe.value.port, null)
      path                                      = probe.value.path
      interval                                  = try(probe.value.interval, 30)
      timeout                                   = try(probe.value.timeout, 30)
      unhealthy_threshold                       = try(probe.value.unhealthy_threshold, 3)
      
          status_code = try(probe.value.match.status_code, ["200-399",])
          body        = try(probe.value.match.body, null)

**Comment by arnaudlh** [comment]
@iriahk89 can you please review?
