### ISSUE TITLE
Add storage account lifecycle management

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#657]
[azurerm_storage_management_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_management_policy)

We currently do not have a way to apply lifecycle management in CAF to storage accounts. The module needs to be integrated.

**Comment by abdulrabbani00** [comment]
@hriaz - https://github.com/aztfmod/terraform-azurerm-caf/pull/658

**Comment by hriaz** [comment]
Verified in Patch.5.4.4 integration branch. This is operational. Thanks for the PR @abdulrabbani00
