### ISSUE TITLE
Add support for Azure Active Directory Domain Services 

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#660]
As per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service

**Comment by schoenr79** [comment]
in what Milesstone would this be picked up agian @arnaudlh due to it was removed from 2109 .
Or did u face any issues implement that feature.

**Comment by arnaudlh** [comment]
hi @schoenr79 - it was removed out from 2109 to prioritize other features. feel free to pick it up if you like/need it :)

**Comment by schoenr79** [comment]
I think i do.... any instructions from your side @arnaudlh  before i start on that. 
Should the submodule placed beneath _azuread_ folder? or on the same level?

**Comment by arnaudlh** [comment]
> I think i do.... any instructions from your side @arnaudlh  before i start on that. 
> 
> Should the submodule placed beneath _azuread_ folder? or on the same level?

I'd probably see it at same level as azuread tends to have bits from the azuread provider...
