### ISSUE TITLE
Support of lower level Log Analytics workspace in diagnostics module.

### ISSUE THREAD

**Issue by LisenaKiev** [aztfmod/terraform-azurerm-caf#669]
According to CAF architecture our company has deployed a Log Analytics instance on the level1(management subscription) and was going to use it to deploy diagnostic and collect  information for several resources on the level2(connectivity subscription). After attempt of Diagnostics deployment  on the level2 with LA in level1 and investigation has been found that the current Diagnostics module allow to use LA workspace  as diagnostic_destination only from the same level where Diagnostics is implemented. If possible we would like to request  a such modification of Diagnostics module  that will  allow to use LA from lower level as destination  , same as it is possible for other resources  with help of  parament LZ_KEY . At the moment module diagnostic does not accept  LZ_KEY.

Desired configuration.

diagnostics_destinations = {
  log_analytics = {
    central_logs = {
      log_analytics_destination_type = "Dedicated"
      log_analytics_key ="la_level1_workspace"
      lz_key             = "governance"    <-----------  !!!!!!!!!!!!!!!!!!!!!
    }
  }
}

**Comment by arnaudlh** [comment]
hi @LisenaKiev, the diagnostics objects are already carried over at all layers by the landingzones.
if you look into the starter, we define diagnostics at level 0 and use them at level 2: https://github.com/Azure/caf-terraform-landingzones-starter/blob/AL-contoso/configuration/archived/sandpit/level2/networking/hub/configuration.tfvars

**Comment by arnaudlh** [comment]
closing as feature already implemented.
