### ISSUE TITLE
Synapse aad_admin causes Error: Too many list items

### ISSUE THREAD

**Issue by rmahoney249** [aztfmod/terraform-azurerm-caf#686]
When adding an aad_admin to an existing Synapse workspace resource under terraform management the following error is received when refreshing state

```
module.caf.module.synapse_workspaces["edp"].azurerm_synapse_workspace.ws: Refreshing state... [id=/subscriptions/2ff00afb-41ca-4c07-8135-775bac809836/resourceGroups/dev-rg-edp-fwq/providers/Microsoft.Synapse/workspaces/devsywsedpoqs]
...
╷
│ Error: Too many list items
│ 
│   with module.caf.module.synapse_workspaces["edp"].azurerm_synapse_workspace.ws,
│   on /home/vscode/.terraform.cache/modules/caf/modules/analytics/synapse/workspace.tf line 14, in resource "azurerm_synapse_workspace" "ws":
│   14: resource "azurerm_synapse_workspace" "ws" {
│ 
│ Attribute supports 1 item maximum, but config has 3 declared.
╵
```

This syntax is incorrect in [modules/analytics/synapse/workspace.tf](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/analytics/synapse/workspace.tf#L28)
```
  dynamic "aad_admin" {
    for_each = try(var.settings.aad_admin, {})
```
and should be

``` 
  dynamic "aad_admin" {
    for_each = try(var.settings.aad_admin, {}) == {} ? [] : [1]
```

or maybe similar to the azuread_administrator in the mssql_server module:
[https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/databases/mssql_server/server.tf#L13](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/databases/mssql_server/server.tf#L13)

Also the other dynamic blocks in the synapse workspace for azure_devops_repo and github_repo look like they would have the same issue.

**Comment by LaurentLesle** [comment]
@rmahoney249  do you want to submit a PR?
