### ISSUE TITLE
tags: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by nashgongchan** [aztfmod/terraform-azurerm-caf#699]
The tag value cannot overwrite from upper level once its set on the lower/launchpad level

![MicrosoftTeams-image](https://user-images.githubusercontent.com/20581452/135020255-c8962217-f537-4587-a474-1307b99982f2.png)

**Comment by arnaudlh** [comment]
Could not repro under current provider. Closing in the meantime, please reopen if you see it happenning again.
