### ISSUE TITLE
Add service bus on CAF module

### ISSUE THREAD

**Issue by nashgongchan** [aztfmod/terraform-azurerm-caf#700]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_topic

**Comment by hriaz** [comment]
@arnaudlh Please assign this to me. I have an active project I need to write the code for this module anyways.

**Comment by arnaudlh** [comment]
Adding reference to #757 on ramp for 5.5.0

**Comment by arnaudlh** [comment]
Closing as present in 5.5.0
