### ISSUE TITLE
Application Insight's connection string in App Service module

### ISSUE THREAD

**Issue by rickychew77** [aztfmod/terraform-azurerm-caf#72]
https://github.com/aztfmod/terraform-azurerm-caf/blob/1ef24023879ad57fff0ab4b3deff2a8cf9d5328b/modules/webapps/appservice/main.tf#L21

Referring to issue [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1303#issuecomment-707039039), the connection string should be like this instead.
>APPLICATIONINSIGHTS_CONNECTION_STRING = azurerm_application_insights.appinsight.connection_string

**Comment by LaurentLesle** [comment]
Added in 0.4.2
