### ISSUE TITLE
Module virtual_machine_scale_set output id is always null for windows

### ISSUE THREAD

**Issue by dimitrifc** [aztfmod/terraform-azurerm-caf#735]
In `terraform-azurerm-caf/modules/compute/virtual_machine_scale_set/output.tf` the id is 

```
output "id" {
  value = local.os_type == "linux" ? try(azurerm_linux_virtual_machine_scale_set.vmss["linux"].id, null) : try(azurerm_linux_virtual_machine_scale_set.vmss["windows"].id, null)
}
```

Compare to `terraform-azurerm-caf/modules/compute/virtual_machine/output.tf`

```
output "id" {
  value = local.os_type == "linux" ? try(azurerm_linux_virtual_machine.vm["linux"].id, null) : try(azurerm_windows_virtual_machine.vm["windows"].id, null)
}
```

The resource created is of type azurerm_**windows**_virtual_machine_scale_set, not linux when the os_type is windows

The id outputted is therefore always null for a windows vm scale set, making it impossible to refer to the created scale set

**Comment by arnaudlh** [comment]
Closing as in 5.4.6
