### ISSUE TITLE
Issues with Subscriptions module in version 5.4.4

### ISSUE THREAD

**Issue by PrudviS** [aztfmod/terraform-azurerm-caf#741]
Subscriptions module in version 5.4.4  expects both billing_scope_id and subscription_id values to be passed, whereas in version 5.4.3, it works with one of them being supplied.

**In version 5.4.4,** 

1. If we don’t pass the billing_scope_id like below,  it fails with the below error at line 14 in modules/subscriptions/subscriptions.tf

![image](https://user-images.githubusercontent.com/65976930/138487361-ab374552-4104-4404-b2c6-760afc30e2c0.png)
![image](https://user-images.githubusercontent.com/65976930/138487378-d8fb75ec-2fd3-454e-b33b-fff3993189dc.png)

2. If we pass both the billing_scope_id and subscription_id values,  it fails with the  error “Invalid combination of arguments” error at lines 13 and  14 in modules/subscriptions/subscriptions.tf,as the resource azurerm_sub expects only one of billing_scope_id or subscription_id values to be passed

![image](https://user-images.githubusercontent.com/65976930/138487603-2a82c77c-b076-4fe1-96d3-2da4d7ec0ef5.png)
![image](https://user-images.githubusercontent.com/65976930/138487630-a0aa89d4-1547-4e73-9065-46831fd03e6e.png)

3. If we don’t pass subscription_id at all, it expects enrollment_account_name and billing_account_name values to be passed 

![image](https://user-images.githubusercontent.com/65976930/138487692-55d6878d-291b-4250-ba3c-788269b7cb31.png)
![image](https://user-images.githubusercontent.com/65976930/138487724-170062ac-d549-4537-9c3a-5b0975bec606.png)

4. If enrollment_account_name and billing_account_name are supplied and subscription_id is not set,  it fails with the below error at line 5 in  modules/subscriptions/diagnostics.tf

![image](https://user-images.githubusercontent.com/65976930/138487994-207d4166-2180-4231-a473-e0bcdfd43664.png)
![image](https://user-images.githubusercontent.com/65976930/138488014-7a4f6a0c-126c-4500-9949-950ad0520424.png)

managed to get the plan working locally by updating line 14 in subscriptions.tf like below

![image](https://user-images.githubusercontent.com/65976930/138488162-aefb7279-c52b-403a-b0ef-79a120ddac50.png)

**Comment by arnaudlh** [comment]
Closing as fixed in 5.4.6
