### ISSUE TITLE
MSSQL server does not support Transparent Data Encryption( TDE)

### ISSUE THREAD

**Issue by riyasriy** [aztfmod/terraform-azurerm-caf#747]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_transparent_data_encryption

For, mssql server transparent data encryption is supported. However TDE is not updated in CAF module(databases).
please update support for TDE

**Comment by arnaudlh** [comment]
Closing as in 5.4.6
