### ISSUE TITLE
Remove tls_private_key resource

### ISSUE THREAD

**Issue by jwygoda** [aztfmod/terraform-azurerm-caf#750]
The private key generated by `tls_private_key` is stored unencrypted in the Terraform state file. Use of this resource for production deployments is not recommended [1].

Following files reference `tls_private_key` resource:
`modules/compute/virtual_machine/vm_linux.tf`
`modules/compute/virtual_machine_scale_set/vmss_linux.tf`

[1] https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key

**Comment by LaurentLesle** [comment]
From now you need to properly secure the access to the tfstates. I am going to close it. Feel free to re-opened with a proposed solution if needed.
