### ISSUE TITLE
Using groups in keyvault access policies causes destroy error

### ISSUE THREAD

**Issue by brk3** [aztfmod/terraform-azurerm-caf#762]
If I use a group to control my keyvault access policy, e.g.

```
azuread_groups = {
  keyvault_level0_rw = {
     ...
  }
}

keyvaults = {
  level0 = {
    ...
  }
}

keyvault_access_policies = {
  level0 = {
    keyvault_level0_rw = {
      azuread_group_key  = "keyvault_level0_rw"
      secret_permissions = ["Set", "Get", "List", "Delete", "Purge", "Recover"]
    }
  }
}
```

Then when running terraform(rover) destroy, I get a permission error. This happens because the assignment is removed from the AD group before terraform attempts to clean up the secrets in the vault.

It would appear a `depends_on` is needed around the secrets and azuread modules, I've yet to find one that works and doesn't cause a circular dependency.

**Comment by arnaudlh** [comment]
Thanks for the issue @brk3 - let us know if any new developments. Adding @SergioMiyama in case is needed.

**Comment by arnaudlh** [comment]
Closing as resolved
