### ISSUE TITLE
Need support for storage account encryption scope to use customer managed key

### ISSUE THREAD

**Issue by riyasriy** [aztfmod/terraform-azurerm-caf#772]
Currently customer managed key is supported in storage account encryption. Need support for customer managed key to be used in encryption scopes.

**Comment by LaurentLesle** [comment]
Closing as supported with customer_managed_key in https://github.com/aztfmod/terraform-azurerm-caf/blob/main/examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars
