### ISSUE TITLE
Add initial support for CosmosDB

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#79]
Initial support for Cosmos DB into CAF module, as per https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html 

- [x] Account (Rahul)
- [x] SQL (Rahul)
- [x] Cassandra (Ben)
- [x] Mongo (Ben) - Still pending https://github.com/terraform-providers/terraform-provider-azurerm/issues/8660 to be resolved 
- [ ] Gremlin (Ben)
- [ ] Table (Ben) 

- [ ] Add diagnostics capabilities

**Comment by singh-rahul** [comment]
Work in progress

**Comment by singh-rahul** [comment]
- Created Cosmos account, 
SQL database & Container.

**Comment by bhummerstone** [comment]
Table API PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/214

**Comment by bhummerstone** [comment]
Cassandra API PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/217

**Comment by bhummerstone** [comment]
Gremlin API PR: https://github.com/aztfmod/terraform-azurerm-caf/pull/218

**Comment by bhummerstone** [comment]
Refactoring of Mongo API for consistency with module hierarchy: https://github.com/aztfmod/terraform-azurerm-caf/pull/219
