### ISSUE TITLE
Role assignments  for Recovery Vault Managed Identity  does not work

### ISSUE THREAD

**Issue by PrudviS** [aztfmod/terraform-azurerm-caf#800]
The current recovery vault module code has identity type set to “SystemAssigned” for the resource "azurerm_recovery_services_vault"
![image](https://user-images.githubusercontent.com/65976930/142022737-a3010862-a4c6-4c5b-9418-9e1ad6d54a6c.png)

We currently are limited using this system assigned identity to perform  role assignments on other resources as principal_id is not included in the outputs of the recovery services vault module

Encountered the below error message when tried with a sample configuration like below
![image](https://user-images.githubusercontent.com/65976930/142022972-31853f60-666a-4d5c-9762-41118c1949e9.png)
![image](https://user-images.githubusercontent.com/65976930/142022995-5ad6d90d-11f9-466e-afcd-d7b9e94e5e18.png)

I’ve managed to get the role assignment working by including the below output in the recovery vault module
![image](https://user-images.githubusercontent.com/65976930/142025142-77777738-e33b-4dab-a235-2a53ba59a0b1.png)

An example use case for this scenario  is that the vault deployed for site recovery replication needs both contributor and Storage Blob Data Contributor privileges on the cache storage account. See  extract  from the documentation below

![image](https://user-images.githubusercontent.com/65976930/142023315-b25d33d7-9b39-49a5-915a-18bdcd5a1ebd.png)

**Comment by arnaudlh** [comment]
thanks @PrudviS, do you want to open the PR to address it?

**Comment by PrudviS** [comment]
Hi @arnaudlh , 
Thank you for the feedback.
I have now submitted the pull request (#827)
