### ISSUE TITLE
Unable to refer existing vnet in AKS cluster creation

### ISSUE THREAD

**Issue by alisha-dev** [aztfmod/terraform-azurerm-caf#810]
I want to deploy AKS cluster in existing vnet created manually or other landingzone. Unfortunately, I am unable to refer existing vnet name while creating an AKS cluster. It always asks to deploy new vnet along with aks setup

**Comment by SergioMiyama** [comment]
Hi Alisha,
I added an example on how to use existing vnet/subnet while deploying an AKS cluster.
`      #subnet_key            = "aks_nodepool_system"
      subnet = {
        key = "aks_nodepool_system"
        #resource_id = "/subscriptions/97958dac-xxxx-xxxx-xxxx-9f436fa73bd4/resourceGroups/qxgc-rg-aks-re1/providers/Microsoft.Network/virtualNetworks/qxgc-vnet-aks/subnets/qxgc-snet-aks_nodepool_system"
      }`
https://github.com/aztfmod/terraform-azurerm-caf/blob/sm-external-subnet/examples/compute/kubernetes_services/101-single-cluster/aks.tfvars

**Comment by alisha-dev** [comment]
Thanks for the response, I am unable to access the link you've shared @SergioMiyama
