### ISSUE TITLE
Unable to refer existing vnet while deploying vmss

### ISSUE THREAD

**Issue by alisha-dev** [aztfmod/terraform-azurerm-caf#811]
I should be able to deploy vmss service in existing vnet created either manually or in other landing zone. 

The current configuration and modules doesn't support that.

**Comment by tenletters10** [comment]
I am running into the same issue, but with normal virtual machines. Can add one to a new vnet created during the creation of the vm, but can't reference an existing vnet.

**Comment by alisha-dev** [comment]
Thanks for the quick fix. I hope this will work for existing vnet and subnet.(created in earlier level, manually or different landingzone) :)

**Comment by alisha-dev** [comment]
This solution is not working as expected. more details here https://github.com/aztfmod/terraform-azurerm-caf/issues/819
