### ISSUE TITLE
 Unable to refer the routetable and nsg in while creating subnet in the existing Vnet.

### ISSUE THREAD

**Issue by alisha-dev** [aztfmod/terraform-azurerm-caf#812]
I am unable to refer the routetable and nsg in while creating subnet in the existing Vnet.
```
  subnetnew3 = {
      name = "newsubnet3"
      cidr = ["10.100.100.32/28"]
      nsg_key = "test"
      route_table_key = "no_internet-test"
      vnet = {
         id = "/subscriptions/xyzzzzz/resourceGroups/launchpad-level1t/providers/Microsoft.Network/virtualNetworks/jtnn-vnet"
         #lz_key  = "foundations"
         #key =   "vnet_region1"
      }
    }
}
```
the above definition is giving the below error.
```
Terraform returned errors:
╷
│ Error: Invalid index
│ 
│   on /home/vscode/.terraform.cache/modules/solution/networking.tf line 84, in resource "azurerm_subnet_route_table_association" "rt":
│   84:   route_table_id = module.route_tables[each.value.route_table_key].id
│     ├────────────────
│     │ each.value.route_table_key is "no_internet-test-tier1"
│     │ module.route_tables is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
```

**Comment by LaurentLesle** [comment]
closing as - https://github.com/aztfmod/terraform-azurerm-caf/blob/main/examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/configuration.tfvars

Make sure you have created the route_tables and azurerm_routes - https://github.com/aztfmod/terraform-azurerm-caf/blob/main/examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/routes.tfvars

https://github.com/aztfmod/terraform-azurerm-caf/blob/e356d54b1d551c7d802419a827db3612cb67c170/examples/networking/virtual_network/102-simple-vnet-special-subnet-udr/configuration.tfvars#L50
