### ISSUE TITLE
Errors in Redis creation during terraform apply

### ISSUE THREAD

**Issue by amadkamal** [aztfmod/terraform-azurerm-caf#815]
We have redis cache configuration that give errors during terraform apply as below

`Error: waiting for the create of Redis Cache "" (Resource Group ""): Code="Failed" Message="The async operation failed." AdditionalInfo=[{"id":"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Cache/Redis/xxx,"location":"Southeast Asia","name":"ptazsg-4asuatb7rc","properties":{"accessKeys":null,"enableNonSslPort":false,"hostName":"xxxx.redis.cache.windows.net","instances":[{"isMaster":false,"isPrimary":false,"sslPort":15000}],"linkedServers":[],"minimumTlsVersion":"1.2","port":6379,"provisioningState":"Failed","publicNetworkAccess":"Enabled","redisConfiguration":{"maxclients":"256","maxfragmentationmemory-reserved":"12","maxmemory-delta":"2","maxmemory-reserved":"2"},"redisVersion":"4.0.14","sku":{"capacity":0,"family":"C","name":"Basic"},"sslPort":6380},"tags":{"ApplicationId":"ApplicationIdTagging","ApplicationName":"ApplicationNameTagging","Application_Classification":"Standard","BIALRAClassification":"Severe","BusinessOPU_HCU":"BusinessOPU_HCU","BusinessOwner":"BusinessOwnerTagging","BusinessStream":"BusinessStream","CSBIA_Availability":"Severe","CSBIA_Confidentiality":"Severe","CSBIA_ImpactScore":"Severe","CSBIA_Integrity":"Severe","CostCenter":"CostCenterTagging","DataClassification":"DataClassificationTagging","Data_Classification":"Internal","IACManaged":"True","IACRepo":"","Name":"ASE IMPROVEMENT PROGRAM","PatchPolicy":"PatchPolicyTagging","ProductOwner":"ProductOwnerTagging","ProductSupport":"ProductSupportTagging","Project_Code":"Project_CodeTagging","SCAClassification":"SCAClassificationTagging","environment":"dev","level":"level3","module":"redis_cache","rover_version":"aztfmod/rover:1.0.4-2108.1802"},"type":"Microsoft.Cache/Redis"}]
│ 
│   with module.solution.module.redis_caches["xxxxx"].azurerm_redis_cache.redis,
│   on /home/vsts_azpcontainer/modules/solution/modules/redis_cache/module.tf line 14, in resource "azurerm_redis_cache" "redis":
│   14: resource "azurerm_redis_cache" "redis" {
│ 
╵
`

**Comment by arnaudlh** [comment]
hi @amadkamal, It feels like a transient error on Azure platform, can you confirm you are still experimenting the issue? cc: @jorseng and @iriahk89.

**Comment by iriahk89** [comment]
yes @arnaudlh. solved with support today. will close the issue :)
