### ISSUE TITLE
Terraform template provider deprecated

### ISSUE THREAD

**Issue by hyperfocus1337** [aztfmod/terraform-azurerm-caf#820]
I'm currently unable to install the `template` [resource](https://registry.terraform.io/providers/hashicorp/template/latest) on my M1 MacBook due to it being deprecated. The resource page states:

```
This provider has been archived. Please use the `templatefile` function or the `Cloudinit` provider instead. See documentation for more details.
```

Facing the following problem after running `terraform init`
```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this
│ provider may have different platforms supported.
```

This code in [packer.tf](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/shared_image_gallery/packer_service_principal/packer.tf#L12-L38) should be refactored to use the [templatefile](https://www.terraform.io/docs/language/functions/templatefile.html) function. So the template resource becomes redundant (didn't discover any other usages of it so far).

**Comment by arnaudlh** [comment]
@hyperfocus1337 you are right, this is used only in the shared image gallery module. If you have a fix for it, would love it as well to get rid of the old provider :)

**Comment by hyperfocus1337** [comment]
@arnaudlh fixed it.

Only noticed that the `template` dependency is still present on the registry dependency overview: https://registry.terraform.io/modules/aztfmod/caf/azurerm/latest?tab=dependencies

This should disappear after the PR is merged and you publish a new version of the caf module.
