### ISSUE TITLE
Need autoscaling support for App Service, Scale Set

### ISSUE THREAD

**Issue by alisha-dev** [aztfmod/terraform-azurerm-caf#822]
The current App service, Scale set module don't support autoscaling. It'd be great to have the support enabled to be used for different scenarios.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting

**Comment by arnaudlh** [comment]
@alisha-dev have you checked https://github.com/aztfmod/terraform-azurerm-caf/pull/803?
