### ISSUE TITLE
Missing ability to reference custom images built in shared_image_gallery

### ISSUE THREAD

**Issue by dimitrifc** [aztfmod/terraform-azurerm-caf#825]
We're using the [shared image gallery module](https://github.com/aztfmod/terraform-azurerm-caf/tree/master/modules/shared_image_gallery) to build custom images. The virtual_machine_scale_set and virtual_machine modules seem to offer the option to specify the custom_image_ids but these are not an output for the shared_image_gallery module:

https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/compute/virtual_machine_scale_set/vmss_windows.tf#L142

Am I misinterpreting the code or is this feature missing?

**Comment by LaurentLesle** [comment]
thanks @dimitrifc for reporting the bug.

**Comment by dimitrifc** [comment]
Added PR
