### ISSUE TITLE
Issues with creating private endpoint for recovery vaults AzureBackup sub resource 

### ISSUE THREAD

**Issue by PrudviS** [aztfmod/terraform-azurerm-caf#830]
Private endpoint code for recovery_vault currently has subresource names hardcoded to "AzureSiteRecovery". See below

![image](https://user-images.githubusercontent.com/65976930/143618226-d3952261-2f99-4d04-aa17-7ab9d03f108b.png)

This hard coded value limits the ability to create private endpoints for recovery_vaults “Azure Backup” sub resource. It currently  creates the private endpoint for Azure Site recovery, irrespective of what is specified in the configuration

I have managed to get the private endpoint for Azure Backup deployed successfully locally,  by including the principal_id in the recovery services vault module(addressed as part of the issue #800 and pull request #827)  and additionally updating the code for private endpoint as follows

![image](https://user-images.githubusercontent.com/65976930/143618376-cd7c3c09-e583-4e74-a775-e1bd9e6966f6.png)

Example  configuration for deploying Private endpoint  for recovery vault AzureBackup Subresource below

![image](https://user-images.githubusercontent.com/65976930/143618447-2a3663e5-e2ce-43ad-abff-165594a0a7e0.png)
![image](https://user-images.githubusercontent.com/65976930/143618459-c1583399-6620-44ed-a00c-b086ae3fd073.png)

Note that the Role assignments defined in the configuration above are required  because as per the documentation, managed identity of the vault needs contributor permissions to the below three  resource groups, prior to creating the private endpoint (https://docs.microsoft.com/en-us/azure/backup/private-endpoints)

![image](https://user-images.githubusercontent.com/65976930/143618490-f470bf0c-7279-4b29-8ebe-06ea4e083b1c.png)

If these permissions are not in place, private endpoint deployment fails with the below error message

![image](https://user-images.githubusercontent.com/65976930/143618717-c9843f24-8688-4fde-8596-14fc5846d489.png)

**Comment by LaurentLesle** [comment]
Thanks a lot @PrudviS for raising this issue. Your analysis  and proposed solution make sense to me. Have you been able to submit a PR with that change? You can also add in the PR the example with the correct role mapping

**Comment by PrudviS** [comment]
Hi @LaurentLesle  ,

I have opened pull request #848  to address this. This PR also includes the example
