### ISSUE TITLE
Application Gateway | Unable to reuse existing subnet and vnet 

### ISSUE THREAD

**Issue by alisha-dev** [aztfmod/terraform-azurerm-caf#831]
Seems like [this](https://github.com/aztfmod/terraform-azurerm-caf/pull/823) is not fixed, Getting the below error when trying to use subnet_id

```
Terraform version 0.15 or greater
╷
│ Error: Error in function call
│ 
│   on ../../aztfmod/modules/networking/application_gateway/locals.networking.tf line 35, in locals:
│   35:       cidr = coalesce(
│   36:         try(local.private_vnet.subnets[var.settings.front_end_ip_configurations.private.subnet_key].cidr, null),
│   37:         try(var.settings.front_end_ip_configurations.private.subnet_cidr, null)
│   38:       )
│     ├────────────────
│     │ local.private_vnet is object with no attributes
│     │ var.settings.front_end_ip_configurations.private is object with 5 attributes
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
╵
Terraform plan return code: 1
Error on or near line 287: Error running terraform plan; exiting with status 1

@calling clean_up_variables
cleanup variables
clean_up backend_files
```

**Comment by SergioMiyama** [comment]
Hi @alisha-dev  can you please share your configuration code with me?

**Comment by alisha-dev** [comment]
```
    front_end_ip_configurations = {
      public = {
        name          = "public"
        public_ip_key = "sample-pip"
      }
      private = {
        name                          = "private"
        subnet_id = "/subscriptions/xyz/resourceGroups/xyz/providers/Microsoft.Network/virtualNetworks/xyz-vnet/subnets/xyz-subnet"
        subnet_cidr_index             = 0 # It is possible to have more than one cidr block per subnet
        private_ip_offset             = 4 # e.g. cidrhost(10.10.0.0/25,4) = 10.10.0.4 => AGW private IP address
        private_ip_address_allocation = "Static"
      }
    }
 ```

**Comment by SergioMiyama** [comment]
`      private = {
        name       = "private"
        vnet_key   = "vnet_region1"
        subnet_key = "app-gateway-subnet"
        #subnet_id                     = "/subscriptions/97958dac-xxxx-xxxx-xxxx-9f436fa73bd4/resourceGroups/vupf-rg-example-agw/providers/Microsoft.Network/virtualNetworks/vupf-vnet-app_gateway_vnet/subnets/vupf-snet-app_gateway_subnet"
        #subnet_cidr                   = "10.100.100.0/25"   <----- This line
        subnet_cidr_index             = 0 # It is possible to have more than one cidr block per subnet
        private_ip_offset             = 4 # e.g. cidrhost(10.10.0.0/25,4) = 10.10.0.4 => AGW private IP address
        private_ip_address_allocation = "Static"
      }`


Hi @alisha-dev, when you are using an existing VNET it won't be able to gather the CIDR so you need to declare it as exampled above.


Regards,
Sergio

**Comment by alisha-dev** [comment]
Thanks, It works
