### ISSUE TITLE
Add support for azurerm_postgresql_flexible_server*

### ISSUE THREAD

**Issue by nusrath432** [aztfmod/terraform-azurerm-caf#841]
PR: #865 

Add support for the following:
- azurerm_postgresql_flexible_server
- azurerm_postgresql_flexible_server_configuration
- azurerm_postgresql_flexible_server_database
- azurerm_postgresql_flexible_server_firewall_rule

Related: 
- https://github.com/aztfmod/terraform-provider-azurecaf/issues/137
- https://github.com/Azure/caf-terraform-landingzones/issues/285

**Comment by arnaudlh** [comment]
Thanks for the suggestion @nusrath432 - dependency on provider has been fixed on [provider 1.2.10](https://github.com/aztfmod/terraform-provider-azurecaf/releases/tag/v1.2.10) - thanks for your PR!
