### ISSUE TITLE
Retiring Terraform 0.13 and 0.14 Support from module 5.5.0

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#851]
With the release of the aztfmod/caf/azurerm module we are ending the support for Terrform 0.13 and Terraform 0.14.x.

We need to remove those versions as the aztfmod module is using a terraform provider attribute that is only supported from version 0.15 and above (configuration_aliases)

Use a rover version with 0.15.5 or 1.0.11 or above to use the module with version >= 5.5.0

**Comment by arnaudlh** [comment]
Closing as present in 5.5.0
