### ISSUE TITLE
Network Peering error in multi-subscription environment (worked in portal for multi-subscription and worked with code in a single subscription)

### ISSUE THREAD

**Issue by riteshmehta66** [aztfmod/terraform-azurerm-caf#869]
Error:

Module.solution.azurerm_virtual_network_peering.peering["eus2_hubvnet_TO_cus_hubvnet"]: Creation complete after 1m19s [id=/subscriptions/529659ac-3e4e-4aff-adc4-8c9eb3730988/resourceGroups/xejy-con-dev-hub-ntw-00-00-a-rg-vnet-e2/providers/Microsoft.Network/virtualNetworks/xejy-con-dev-hub-ntw-00-00-a-vnet-00-e2/virtualNetworkPeerings/xejy-con-dev-hub-ntw-00-00-a-peer-e2hch-e2]
╷
│ Error: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=0 – Original Error: Code="ResourceGroupNotFound" Message="Resource group 'xejy-idm-dev-00-idm-00-mhb-a-rg-vnet-c1' could not be found."
│
│   with module.solution.azurerm_virtual_network_peering.peering["cus_identity_spoke1_TO_cus_hubvnet"],
│   on /home/vscode/.terraform.cache/modules/solution/networking.tf line 165, in resource "azurerm_virtual_network_peering" "peering":
│  165: resource "azurerm_virtual_network_peering" "peering" {
│
╵

Code:

eus2_mgmt_spoke1_TO_eus2_hubvnet = {
    name = "con-dev-mgt-ntw-00-00-a-peer-mgs1eh-e2"
    from = {
      lz_key = "caf_level2_vnets_management"
      output_key = "vnets"
      vnet_key = "eus2_vnet_01"
      
    }
    to = {
      lz_key = "caf_level2_vnets_connectivity"
      output_key = "vnets"
      vnet_key = "eus2_vnet_01"
    }
    
    allow_virtual_network_access = true
    allow_forwarded_traffic      = true  
    allow_gateway_transit        = false  
    use_remote_gateways          = false
  }

**Comment by hriaz** [comment]
@riteshmehta66 This is normal behavior. When you create a VNET peer you do source -> destination. You then need to switch the subscription context to create the bi-directional peer. 

1. Create peer from hub to spoke
2. Switch to spoke subscription
3. Create peer from spoke to hub

The portal does that for you. Via powershell you can reference this article [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-peering-different-subscriptions) it will do the exact same thing. 

@arnaudlh @LaurentLesle I don't think there is much that can be done here for this issue

**Comment by riteshmehta66** [comment]
Yes. It worked closing the issue. Thanks!
