### ISSUE TITLE
sqlmi cannot use the same subnet which has been used

### ISSUE THREAD

**Issue by nashgongchan** [aztfmod/terraform-azurerm-caf#872]

**Comment by iriahk89** [comment]
@arnaudlh this happened after latest commit on sql mi in this changeset: https://github.com/aztfmod/terraform-azurerm-caf/commit/6d13c90e38b0545b5834169f0f5fd6a60246983b#diff-132729985186114a465bf6f4eb80eb4615b6efb5859649a47c2e6afb8eab8992

@SergioMiyama I assigned to you as the latest commit is yours

**Comment by iriahk89** [comment]
they reported that even different subnet also not possible now to deploy sql mi
