### ISSUE TITLE
This block needs update to the code to support centralized LAW across the region.

### ISSUE THREAD

**Issue by mh-riteshmehta** [aztfmod/terraform-azurerm-caf#873]
This block needs update to the code to support centralized LAW across the region.

traffic_analytics = {
    enabled                             = true
Request to update code to support Centralized LAW in different region. In portal LAW in different region works
    log_analytics_workspace_destination = "cus_logs"     # This needs update to support centralized LAW acroos the region  
    interval_in_minutes                 = "10"
  }

_Originally posted by @riteshmehta66 in https://github.com/aztfmod/terraform-azurerm-caf/issues/870#issuecomment-993530739_

**Comment by riteshmehta66** [comment]
mistake. closing. Original issue #870 still open
