### ISSUE TITLE
SQL managed instances using azurerm_sql_managed_instance resource

### ISSUE THREAD

**Issue by hyperfocus1337** [aztfmod/terraform-azurerm-caf#902]
I noticed that the SQL managed instances are being created with the [azurerm_template_deployment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/template_deployment) resource in the [code](https://github.com/VolkerWessels/terraform-azurerm-caf/blob/master/modules/databases/mssql_managed_instance/managed_instance.tf#L11-L28) using an ARM template, even though there is a [azurerm_sql_managed_instances](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance) resource available.

Issue https://github.com/aztfmod/terraform-azurerm-caf/issues/106 does not mention anything regarding the considerations as to why the functionality was built into the CAF framework this way.

Any reason as to why it was done this way, instead of using the approriate resource?

Would it be an improvement to change the code to use the [azurerm_sql_managed_instances](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance) resource instead?

**Comment by arnaudlh** [comment]
@hyperfocus1337 the provider was not working for sqlmi for a long time and thats why we had it in ARM template snippets. Happy to take a PR to implementing it :)

**Comment by arnaudlh** [comment]
Duplicates of 983, closing this one.
