### ISSUE TITLE
Unable to use this module with azuread resources

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#913]
I was trying to create a new azuread_application, but it seems to be impossible with new service principals. As far as I understood this module is using **azuread** provider in version 1.4.0, but this means it's not supporting Microsoft Graph (support starts at [1.5.0](https://github.com/hashicorp/terraform-provider-azuread/releases/tag/v1.5.0)). 

The problem here is that Azure Active Directory Graph will be **deprecated in June 2022** and newly created service principals are not allowed to use it anymore. Are there any plans to update azuread provider @arnaudlh  ? 

Notification in MS Portal:
```
Azure Active Directory Graph will be deprecated in June 2022. We recommend 
using Microsoft Graph APIs for your application. If you are currently using Azure 
Active Directory Graph, please migrate to Microsoft Graph.
```

**Comment by arnaudlh** [comment]
Just an interim udpate @wasfree, dev work is in progress and we should have the first bits soon. 
Thanks @SergioMiyama for working on it :)

**Comment by arnaudlh** [comment]
Thanks for bearing with us on this one, in the meantinme the PR and working branch is here: https://github.com/aztfmod/terraform-azurerm-caf/pull/1255

**Comment by arnaudlh** [comment]
This should be ok starting module 5.7.0!
