### ISSUE TITLE
[Feature] Mysql Flexible Server

### ISSUE THREAD

**Issue by hriaz** [aztfmod/terraform-azurerm-caf#915]
This is a place holder issue for MySQL flexible server. This is currently missing in CAF and our team is starting to work on this.

**Comment by arnaudlh** [comment]
Thanks @hriaz, this has been submitted in this PR https://github.com/aztfmod/terraform-azurerm-caf/pull/865 and is on ramp for 5.5.2. Please let us know if something is missing from this PR!

**Comment by hriaz** [comment]
@arnaudlh The PR that was submitted is for PostgresSQL and this one is for MySQL Flexible server.
