### ISSUE TITLE
Add Support for Azure Red Hat OpenShift

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-azurerm-caf#927]
Once this PR get merged: 
https://github.com/hashicorp/terraform-provider-azurerm/pull/15262 and Issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/3614

**Comment by gevraud-cicd** [comment]
Hello,

do you have any idea when it will be merged ?

Regards

**Comment by arnaudlh** [comment]
hi @gevraud-cicd - Based on the velocity of https://github.com/hashicorp/terraform-provider-azurerm/pull/15262 - we are considering an AZPI version of it.

**Comment by gevraud-cicd** [comment]
Hello,

What is AZPI ?

Regards

**Comment by arnaudlh** [comment]
https://registry.terraform.io/providers/Azure/azapi/0.5.0

**Comment by arnaudlh** [comment]
I will push a first working branch in the next days.
