### ISSUE TITLE
NSG_Flow_Logs --> storage account and log analytic workspace

### ISSUE THREAD

**Issue by AgusAlfenrando** [aztfmod/terraform-azurerm-caf#930]
Hi,
I'm trying to create NSG flow logs and I already create a storage account in level 1 and log analytic in level 1. and I want to call the lz_key from level 3 in Network_security_group_definition.tfvars to connect storage account in level 1 and log analytic in level 1.

but if I see in the module of nsg_flow and the error message shown that I don't have lz_key variable for storage account and log analytic.

![Capture](https://user-images.githubusercontent.com/48276446/153160798-ef5f5a60-7642-4876-86b4-465b0b2b1974.PNG)

do we need lz_key to connect storage account in level 1 to Network_security_group_definition.tfvars to create nsg flow or if not needed. is there any workaround for this? pls advice.

Thanks

**Comment by hriaz** [comment]
Make sure your level 2 was redeployed after you created the storage account in Level 1. CAF cascades the state files and appends data from previous levels. So if you make a change in Level 1 and then try to reference in Level 3, it will fail. You need to run tf apply in level 2 and then level 3 would recognize it.

**Comment by AgusAlfenrando** [comment]
ok let me try first. thank you @hriaz

**Comment by AgusAlfenrando** [comment]
Hi @hriaz , if I already deploy storage account to level 2 but in  the module in CAF I don't see lz_key in storage account in the nsg flow. is it possible to call storage account in level 2?

![image](https://user-images.githubusercontent.com/48276446/154015506-528e7702-c023-4bfb-acca-a286d3430264.png)

![image](https://user-images.githubusercontent.com/48276446/154015849-f2e5f4bc-2db1-4752-bfc8-60d2b821ae48.png)

thank you
