### ISSUE TITLE
Incorrect resource type specified for APIM

### ISSUE THREAD

**Issue by brianfedorcrowe** [aztfmod/terraform-azurerm-caf#934]
File: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/apim/api_management/module.tf

We recently upgraded to 5.5.1 to use the APIM module. We noticed on line 3 of the module that "resource_type" is set to "azurerm_data_factory" instead of "azurerm_api_management". This causes the prefix of the deployed APIM instance to be "adf-" instead of "apim-". Is there a reason that this was necessary or is possible to use "azurerm_api_management"?

I had reached out to both of the most recent contributors via gitter, but have not received a response from either, which is why I'm now submitting this as an issue.

**Comment by SergioMiyama** [comment]
@brianfedorcrowe 
#936 Hi Brian just did a PR on this issue.

**Comment by brianfedorcrowe** [comment]
This looks solid to me. How can we get someone to merge in the changes?
