### ISSUE TITLE
[ERROR] App Gateway - backend_pools still creating even after 30 minutes run and still going 

### ISSUE THREAD

**Issue by AgusAlfenrando** [aztfmod/terraform-azurerm-caf#937]
So I try to apply App gateway. 
when I first try using "plan" everything works fine there is no error in my visual studio code.
But when I tried to "apply" the backend to the azure.
there is an error in backendpool where the backendpool still creating even after 30 minutes and it's still going.

Here's the attached are my backend_pools code.
Is there any wrong with my code? or should I use FQDN instead IP Address ? 

Any advise ?
Thank you

![AppgatewayBackEndPoolError](https://user-images.githubusercontent.com/48276446/154012078-d4ac863c-6570-41af-a684-773990bf362e.png)

**Comment by arnaudlh** [comment]
hi @AgusAlfenrando, as long as it runs, it runs :) does it end up working or do you experiment an error with a timeout at apply stage? 
thanks

**Comment by AgusAlfenrando** [comment]
hi @arnaudlh , I apply it this until 2 hour and I still don't get a time out. perhaps I will try again and wait until it timeout.

**Comment by arnaudlh** [comment]
As taken offline, this might be a bug related to the ```affinitycookiename``` with an extra space in https://github.com/aztfmod/terraform-azurerm-caf/blob/04fc03ea7d4ab9c9e7da5968aafed2d51fb72220/modules/networking/application_gateway_application/scripts/set_resource.sh#L89. 

Will correct this in 5.5.3, appreciate if you are able to test locally and confirm it fixes the problem
