### ISSUE TITLE
Reference an existing boot diagnostics storage account & key vault for multiple VMSS across landing zones

### ISSUE THREAD

**Issue by ianlimle** [aztfmod/terraform-azurerm-caf#938]
Hi @SergioMiyama I have a use case where I'm trying to reference a shared boot diagnostics storage account and shared key vault across multiple virtual machine scale sets. 

In the existing infrastructure setup, we have an existing boot diagnostics storage account and key vault. 

Is there a way for the virtual_machine_scale_sets resource to reference the same existing boot diagnostic storage account and existing key vault instead of creating new ones? 

If possible, we would like to perform this referencing of the existing boot diagnostics storage account & key vault in CAF across landing zones.

The code block below works 
```
virtual_machines = {

  vm1 = {
    resource_group_key                   = "vm_single_re2"
    provision_vm_agent                   = true
    os_type                              = "linux"
    keyvault_key                         = "kv1"
    boot_diagnostics_storage_account_key = "bootdiag1"
    
   ... 
```

**Comment by florian-ried** [comment]
@ianlimle 
I'm just facing the same question. How do I reference a central boot diagnostic storage account that is in a different landing zone for multiple VMs? I've tried the following, but unfortunately without success.

![image](https://user-images.githubusercontent.com/95634472/195865112-4005a2bf-9119-4d20-963a-36de014f8d53.png)

**Comment by jikuja** [comment]
Do you have some special use case to use storage account for boot diagnostics?

Managed boot diagnostics storage account is the recommended option: https://learn.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#boot-diagnostics-storage-account

On API-level: https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#bootdiagnostics

**Comment by ianlim-cldcvr** [comment]
@florian-ried we were able to point the vm to reference a central boot diagnostic storage account in a remote landing zone via this
```
virtual_machines = {

  vm1 = {
    lz_key = "remote_bootdiag"
    boot_diagnostics_storage_account_key = "bootdiag1"
   ...
```
