### ISSUE TITLE
Unable to update keyvault secrets in module version 5.5.2

### ISSUE THREAD

**Issue by wasfree** [aztfmod/terraform-azurerm-caf#939]
We just run into issues with updating keyvault secrets with this module in version 5.5.2. It seems there has something changed in behavior of azure keyvault secret value changes. After looking into the module we figured out there was a lifecycle>ignore_changes block added. Unfortunately this change was made without any explanation or PR to understand why it was added.

@LaurentLesle can you please give us a heads-up on this? We would like to be able to update our keyvault secrets.
https://github.com/aztfmod/terraform-azurerm-caf/commit/2fb69c53fc3db9f572a2cc2f7b31564da97d0729

**Comment by arnaudlh** [comment]
good catch @wasfree, we have a repro and a fix that will be in 5.5.4 to be released soon!
