### ISSUE TITLE
Change the resource_group_key in both firewall and EX_circuit

### ISSUE THREAD

**Issue by anasmohana** [aztfmod/terraform-azurerm-caf#943]
I have faced a problem when I have tried to deploy a new firewall and express router circuit to the virtual hub that both this resource does not accept a resource group input as a remote one (lz_key & key) and the only workaround is to create a new RG in hub LZ. I prefer to add more flexibility to send these resources to another RG.

**Comment by arnaudlh** [comment]
hi @anasmohana, can you paste your config example so we can review? thanks

**Comment by anasmohana** [comment]
Hi here is the code for the firewall
``
resource_groups = {
  firewall_wan = {
    name   = "firewall-wan"
    region = "region1"
  }
}

azurerm_firewalls = {
  firewall = {
    name               = "bt-firewall"
    sku_name           = "AZFW_Hub"
    sku_tier           = "Standard"
    resource_group_key = "firewall_wan"
    zones              = ["1"]
    virtual_hub = {
      hub1 = {
        virtual_hub_id  = "/subscriptions/a60b7a72-8146-4d1d-8c29-ffb8584cb072/resourceGroups/obftest-rg-connectivity-global-wan/providers/Microsoft.Network/virtualHubs/obftest-vhub-hub1"
        public_ip_count = 4
      }
    }
  }
}
``
Here I have created a new RG to host the firewall because of the firewall.tf file does not support {lz_key/key} please see here:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/6246181/154673050-acd54484-d1a4-4851-bc85-d4b1f1f015b1.png">

I suggest to change this line to be:
  resource_group_name = local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][each.value.resource_group.key].name

**Comment by arnaudlh** [comment]
thanks for submitting the issue @anasmohana!

**Comment by anasmohana** [comment]
I appreciate your feedback 😊
