### ISSUE TITLE
Add support for azurerm_log_analytics_storage_insights 

### ISSUE THREAD

**Issue by ianlim-cldcvr** [aztfmod/terraform-azurerm-caf#958]
Hi @SergioMiyama 

I have a use case where I'm currently trying to pipe logs from any storage account to an existing log analytics workspace. I believe this requires the `azurerm_log_analytics_storage_insights` Terraform resource as per the link here. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_storage_insights. Thank you

**Comment by SergioMiyama** [comment]
@ianlim-cldcvr,
Hi Ian,
I have already implemented the module, and will just add the Name provider to it and it should be good to go.
