### ISSUE TITLE
Virtual hub Connections failed to deploy new connection with remote vnet by using lz-key/key attributes

### ISSUE THREAD

**Issue by anasmohana** [aztfmod/terraform-azurerm-caf#974]
I have designed my solution to collect all connections to hub deployments in one pipeline in level3 and that helps me to have full control over these spoke connections for every new lanadng zone. but I got a bug that the vhub connections failed when I use lz-key/key attributes:
/home/vsts_azpcontainer/prod/rover_jobs/20220301122227437105712/modules/solution/networking_virtual_hub_connection.tf line 20, in resource "azurerm_virtual_hub_connection" "vhub_connection":
  20:   remote_virtual_network_id = coalesce(
  21:     try(local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][each.value.vnet.vnet_key].id, ""),
  22:     try(each.value.vnet.resource_id, "")
  23:   )
    ├────────────────
    │ each.value.vnet is object with 2 attributes
    │ each.value.vnet.lz_key is "infoblox_lz"
    │ each.value.vnet.vnet_key is "vnet_infoblox"
    │ local.client_config.landingzone_key is "hub_connections"
    │ local.combined_objects_networking is object with 4 attributes
Call to function "coalesce" failed: no non-null, non-empty-string arguments.
 
and as a workaround, I have used a resource_id.

this config works dosent't work:
virtual_hub_connections = {
  infoblox_spoke_TO_hub_con = {
    name = "infoblox_spoke_TO_hub_con"
    virtual_hub = {
      lz_key = "connectivity_virtual_hub1"
      key    = "hub1"
    }
    vnet = {
      lz_key ="xxxx"
      vnet_key = "xxxxx"
    }
  }
}
the level that has this vnet is the current level3, but another config folder. and it is included in the landingzone block.

**Comment by arnaudlh** [comment]
hi @anasmohana can you try with branch ```patch.5.5.4```, it changes the association pattern and should resolve your issue. please let me know!

**Comment by anasmohana** [comment]
I have tested now and both firewall and express router circuits working fine now with resource group = lz-key/key.
another thing want to share with you is I have written a new add-ons module to deploy Infoblox to azure by using templet and think to open a new pull request for that is that ok

**Comment by arnaudlh** [comment]
thanks for your quick confirmation @anasmohana! on the add-on, i think that would definitely be a good addition for azurelz (https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution/add-ons) !
