### ISSUE TITLE
Data Factory Global Parameters not getting found from tfvars

### ISSUE THREAD

**Issue by brianfedorcrowe** [aztfmod/terraform-azurerm-caf#979]
Module: https://github.com/aztfmod/terraform-azurerm-caf/blob/5a0627ea5029e212f1fe798ed7ff8615b61e96af/modules/data_factory/data_factory/module.tf

**Issue 1:** Should the setting name be "global_parameters" to be consistent with how other modules reference setting blocks that can have multiple settings? If agreed, I'll proceed with using this name in the example below instead of "global_parameter".

**Issue 2:** The code below is looking for a "global_parameter" setting. When it finds one, however, it used what is in the "vsts_configuration" setting instead. Possible copy-paste oversight?

Code (Line 28):
`    for_each = try(var.settings.global_parameter, null) != null ? [var.settings.vsts_configuration] : []`
    
Correction:
`    for_each = try(var.settings.global_parameters, null) != null ? [var.settings.global_parameters] : []`

The effect of this issue is that the global parameter block is not being found from tfvars, which means that they do not get created, even when they are defined correctly.

**Comment by arnaudlh** [comment]
hi @brianfedorcrowe regarding ```global_parameter``` its the name as per https://registry.terraform.io/providers/hashicorp/azurerm/2.88.1/docs/resources/data_factory. We pluralize name for top-level resources but normally should not do it for settings inside the objects.

Regarding the iterator on L28, agree its a defect. I'm going to fix it directly in 5.5.4 as we are in final edits. 
Thanks for reporting it!
