### ISSUE TITLE
WAF Support for OWASP 3.2 upper limit above 128kb

### ISSUE THREAD

**Issue by jorseng** [aztfmod/terraform-azurerm-caf#981]
Support requested to implement higher upper limit for OWASP 3.2 above 128kb, which is now supported in terraform provider version above v2.91.0. in 

https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.91.0/CHANGELOG.md

resource: azurerm_web_application_firewall_policy

**Comment by arnaudlh** [comment]
Feel free to use branch ```AL-azurerm2931``` as base since it uses 2.98 or 2.99 depending on quality.

**Comment by arnaudlh** [comment]
Closing as provider updated.
