### ISSUE TITLE
SQL MI native Terraform development

### ISSUE THREAD

**Issue by jorseng** [aztfmod/terraform-azurerm-caf#983]
Terraform has released support for SQLMI, update current SQLMI module from ARM template to native terraform API.

**Comment by arnaudlh** [comment]
Duplicates with https://github.com/aztfmod/terraform-azurerm-caf/issues/902.
@jorseng do you have bandwidth to work on this one?

**Comment by arnaudlh** [comment]
Closing as released in 5.7.0!
