### ISSUE TITLE
code review - refactor resource injection in private modules

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf#987]
Following the February bug bash review consider a transition from using try() to can() to allow values to be evaluated at plan time.

- [ ] keyvault_certificate_issuers.tf (keyvault_id and password)
- [ ] mariadb_servers (keyvault_id, subnet_id, private_endpoints, resource_groups)
- [ ] modules/networking/firewall/module.tf (subnet_id)
- [ ] msssql_managed_databases.tf (db_name, sourceDatabaseId)
- [ ] msssql_managed_instances.tf (subnet_id, keyvault_id, mi_name)
- [ ] mysql_servers.tf (keyvault_id, subnet_id)
- [ ] networking_domain_name_registrations.tf (dns_zone_id)
- [ ] networking_ip_groups.tf (vnets)
- [ ] networking_nat_gateways.tf (subnet_id, public_ip_address_id)
- [ ] networking_virtual_hub_er_connection.tf (virtual_network_gateway_id)
- [ ] networking_vngw.tf (virtual_network_gateway_id)
- [ ] postgresql_servers.tf (keyvault_id, subnet_id)

**Comment by arnaudlh** [comment]
Closing as fixed in 5.5.x
