### ISSUE TITLE
Data factory dynamic iteration not working for global_parameter

### ISSUE THREAD

**Issue by brianfedorcrowe** [aztfmod/terraform-azurerm-caf#990]
As a follow up to issue: https://github.com/aztfmod/terraform-azurerm-caf/issues/979

[The logic for the global_parameter](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/data_factory/data_factory/module.tf) is not working in that it does not pick up the global parameters in the list as defined in tfvars. The current logic in the module is as follows:

```
resource "azurerm_data_factory" "df" {
...
  dynamic "global_parameter" {
    for_each = try(var.settings.global_parameter, null) != null ? [var.settings.global_parameter] : []

    content {
      name  = global_parameter.value.name
      type  = global_parameter.value.type
      value = global_parameter.value.value
    }
  }
...
```
We are defining the list of global parameters in tfvars as follows:

```
data_factory = {
  df = {
    name = "datafactory"
    resource_group = {
      key = "rg1"
    }
    identity = {
      type         = "SystemAssigned"
      identity_ids = []
    }
    vsts_configuration = {
      account_name    = "account_name"
      branch_name     = "branch_name"
      project_name    = "project_name"
      repository_name = "repository_name"
      root_folder     = "root_folder"
      tenant_id       = "tenant_id"
    }
    global_parameter = {
      gp_1 = {
        name  = "GlobalParameter1"
        type  = "String"
        value = "value1"
      }
      gp_2 = {
        name  = "GlobalParameter2"
        type  = "String"
        value = "value1"
      }
      gp_3 = {
        name  = "GlobalParameter3"
        type  = "String"
        value = "value1"
      }
    }
    public_network_enabled = true
  }
}
```

We found that this logic for the global_parameter dynamic iteration works with the global_parameter list as shown above:

```
resource "azurerm_data_factory" "df" {
...
  dynamic "global_parameter" {
    for_each = try(var.data_factory.df.global_parameter, null) != null ? var.data_factory.df.global_parameter : {}

    content {
      name  = global_parameter.value.name
      type  = global_parameter.value.type
      value = global_parameter.value.value
    }
  }
...
}
```

Please note the difference in the for_each line when comparing how it exists in 5.5.4 versus what we found is working when we mock it up ourselves. It's possible that it is simply a matter of using `... var.data_factory.df.global_parameter : {}` instead of `... [var.settings.global_parameter] : []`. 

Also, it may be more in keeping with standards to use _var.settings.global_parameter_ instead of what we tried in our tests, which was _var.data_factory.df.global_parameter_.

Last, if it's likely that we are not defining the list of global parameters in our tfvars in a way that will work with how the for_each logic expects it to be defined, then please provide an example of the appropriate way to do this instead.

Thank you for your time.

**Comment by TjommeVergauwen** [comment]
The suggested global_parameter definition above generates the following error: 
```
Error: Unsupported attribute
│
│   on .terraform\modules\caf\modules\data_factory\data_factory\module.tf line 31, in resource "azurerm_data_factory" "df":
│   31:       name  = global_parameter.value.name
│     ├────────────────
│     │ global_parameter.value is object with 3 attributes
│
│ This object does not have an attribute named "name".

```
Defining just 1 global_parameter block as follows works perfectly
```
global_parameter = {
   name  = "someName"
   type  = "String"
   value = "someValue"
}
```
Defining this block more than once only keeps the last definition.

According to the definition, global_parameter should be a list of blocks. I assume that would be something like:
```
global_parameter = [
      {
        name  = "GlobalParameter1"
        type  = "String"
        value = "value1"
      }
      ,{
        name  = "GlobalParameter2"
        type  = "String"
        value = "value1"
      }
    ]
```
This generates the following error:
```
│ Error: Unsupported attribute
│
│   on .terraform\modules\caf\modules\data_factory\data_factory\module.tf line 31, in resource "azurerm_data_factory" "df":
│   31:       name  = global_parameter.value.name
│     ├────────────────
│     │ global_parameter.value is tuple with 2 elements
│
│ This value does not have any attributes.

```
Any suggestions on how to get this working are appreciated. Maybe add this to the example as well :-)
