### ISSUE TITLE
Enable support for App Configuration

### ISSUE THREAD

**Issue by brianfedorcrowe** [aztfmod/terraform-azurerm-caf#994]
We noticed that [there is an "app_config" variable](https://github.com/aztfmod/terraform-azurerm-caf/blob/18d145588b6d0bba38fef9db71870b52b94e9200/variables.tf#L337), which has been commented out. We also saw [the corresponding module for app_config](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/databases/app_config/app_config.tf), but no examples are available. 

We attempted to uncomment the variable and construct the app_config block in tfvars, but it did not get recognized by `terraform plan`.

Can you please find a way to make app_confg available to be created via CAF Terraform?

**Comment by arnaudlh** [comment]
Hi @brianfedorcrowe, as you can see: https://github.com/aztfmod/terraform-azurerm-caf/blob/18d145588b6d0bba38fef9db71870b52b94e9200/app_config.tf#L3 the code will be activated for ```database.appconfig``` so it would potentially work if you feed it with the right variables :) 

Its true there is no example in the caf_example
1. Variables call https://github.com/aztfmod/terraform-azurerm-caf/blob/18d145588b6d0bba38fef9db71870b52b94e9200/examples/module.tf#L112 
2. Variable files

@SergioMiyama, can you please have a look at it?

**Comment by SergioMiyama** [comment]
Hi @brianfedorcrowe,
I just created and example and a readme doc for the app_conf.

https://github.com/aztfmod/terraform-azurerm-caf/pull/998

**Comment by brianfedorcrowe** [comment]
This is very helpful! We noticed one thing missing from [the output.tf](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/databases/app_config/output.tf), which is the name of the App Config instance. Is that something that you could include in your PR as well?
