### ISSUE TITLE
add dynamic value to the dynamic keyvault secret

### ISSUE THREAD

**Issue by anasmohana** [aztfmod/terraform-azurerm-caf#995]
I have added a new feature to the dynamic key vault secret that allows the user to generate a dynamic password in the new secret.
I have created a new branch but looks like I'm not authorized to push this branch.
I can't share my solution if you are interested even can push a branch and creating a new pull.

**Comment by SergioMiyama** [comment]
Hi @anasmohana, you can actually create Pull Requests to contribute.
To do so first you need to Fork the repository, the following link has detailed information on how to do so.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
